### ISSUE TITLE
Error in .log

### ISSUE THREAD

**Issue by Freymuth** [BanManagement/BanManager#170]
[10:23:57] [Server thread/ERROR]: Error occurred while enabling BanManager v5.0.0 (Is it up to date?)
java.lang.IllegalStateException: Could not get next result for class me.confuser.banmanager.data.IpBanData
	at me.confuser.banmanager.ormlite.stmt.SelectIterator.next(SelectIterator.java:183) ~[?:?]
	at me.confuser.banmanager.storage.IpBanStorage.<init>(IpBanStorage.java:39) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:403) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]
Caused by: java.sql.SQLException: Column 'id' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1144) ~[craftbukkit.jar:git-Spigot-35348a5-ee6d0fa]
	at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseResults.findColumn(JdbcDatabaseResults.java:90) ~[?:?]
	at me.confuser.banmanager.ormlite.field.FieldType.resultToJava(FieldType.java:815) ~[?:?]
	at me.confuser.banmanager.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:60) ~[?:?]
	at me.confuser.banmanager.ormlite.stmt.SelectIterator.getCurrent(SelectIterator.java:270) ~[?:?]
	at me.confuser.banmanager.ormlite.stmt.SelectIterator.nextThrow(SelectIterator.java:161) ~[?:?]
	at me.confuser.banmanager.ormlite.stmt.SelectIterator.next(SelectIterator.java:173) ~[?:?]
	... 14 more

**Comment by confuser** [comment]
I can only presume you tried updating from v4, but it has not been done correctly, as your ip bans table has the v4 structure still.

Please follow the instructions carefully.
