### ISSUE TITLE
Migration failure for almost every entry

### ISSUE THREAD

**Issue by gdude2002** [BanManagement/BanManager#174]
Seems to be a constraint problem.

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'O\x10\v\xC9\x01F\xD0\x85\x11,\x1F\x80\xFD\x0C\x07' for key 'PRIMARY'
```

I am aware that this could probably happen for people that have been banned and then changed their name, but a notification of that would be better than tons of console spam.

**Comment by confuser** [comment]
That just means the data is already in the database. The conversion process does in fact first check to see if they exist in the database, so I'm not quite sure why you're seeing that.

Can you post the full stack trace please?

**Comment by gdude2002** [comment]
Sure thing.

```
[03:58:09] [Server thread/INFO]: [BanManager] Requesting UUID for megapile at 1422831147
[03:58:09] [Server thread/WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerData@5602a724: INSERT INTO `migrated_players` (`id` ,`name` ,`ip` ,`lastSeen` ) VALUES (?,?,?,?)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.storage.conversion.converters.Converter.findAndCreate(Converter.java:41)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.storage.conversion.converters.PlayerIpConverter.run(PlayerIpConverter.java:29)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.storage.conversion.UUIDConvert.executeConverter(UUIDConvert.java:97)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.storage.conversion.UUIDConvert.<init>(UUIDConvert.java:21)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.BanManager.setupConversion(BanManager.java:166)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:112)
[03:58:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[03:58:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333)
[03:58:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[03:58:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352)
[03:58:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313)
[03:58:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[03:58:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[03:58:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[03:58:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[03:58:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:498)
[03:58:09] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[03:58:09] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '#0\x80L\xD2\x8EC\x12\xAE\x96p\x8F^\xC1\xA6\x84' for key 'PRIMARY'
[03:58:09] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:58:09] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[03:58:09] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:58:09] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[03:58:09] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[03:58:09] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[03:58:09] [Server thread/WARN]: 	... 19 more
```

**Comment by confuser** [comment]
Try latest developer build, it'll be building now.

http://ci.frostcast.net

**Comment by gdude2002** [comment]
Is it safe to restart the migration if Mojang stops sending me UUIDs, btw? That won't nuke everything and restart, right? :P

**Comment by confuser** [comment]
It's safe to keep re-running, yes. It shouldn't duplicate the data.

If you've hit the rate limit, I'd recommend waiting a few minutes before re-running. The route the conversion process uses to take into account name changes, is limited at 600 requests every 10 minutes, i.e. 1 request a second.

**Comment by gdude2002** [comment]
Yeah, I know the rate limit, freakin' Mojang..

It looks like I'm getting the same error, at any rate. I'd get you a log but my terminal is being printed to way too fast right now, lol.

**Comment by gdude2002** [comment]
Aha, here we go.

```
[06:06:05] [Server thread/INFO]: [BanManager] Requesting UUID for zisora at 1423760610
[06:06:05] [Server thread/WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerData@4370e1c5: INSERT INTO `migrated_players` (`id` ,`name` ,`ip` ,`lastSeen` ) VALUES (?,?,?,?)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.storage.conversion.converters.Converter.findAndCreate(Converter.java:41)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.storage.conversion.converters.PlayerIpConverter.run(PlayerIpConverter.java:34)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.storage.conversion.UUIDConvert.executeConverter(UUIDConvert.java:97)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.storage.conversion.UUIDConvert.<init>(UUIDConvert.java:21)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.BanManager.setupConversion(BanManager.java:166)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:112)
[06:06:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[06:06:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333)
[06:06:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[06:06:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352)
[06:06:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313)
[06:06:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[06:06:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[06:06:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[06:06:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[06:06:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:498)
[06:06:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[06:06:05] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry ';\xA0\xC3\xD6\xE1\xC7I|\xBB\x1C;G^!\x99y' for key 'PRIMARY'
[06:06:05] [Server thread/WARN]: 	at sun.reflect.GeneratedConstructorAccessor75.newInstance(Unknown Source)
[06:06:05] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[06:06:05] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[06:06:05] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[06:06:05] [Server thread/WARN]: 	at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[06:06:05] [Server thread/WARN]: 	... 19 more
[06:06:07] [Server thread/INFO]: [BanManager] §aPlayer ips table converted!
```

**Comment by confuser** [comment]
Ok try next build

**Comment by gdude2002** [comment]
Alright, I'm not seeing the errors now, but something else is interesting.

![](http://i.imgur.com/cpFaxZQ.png)

Shouldn't these be cached or something? It'd be considerably faster.

**Comment by confuser** [comment]
It is cached, check your database. The requests must be failing otherwise it would use the cache.

**Comment by gdude2002** [comment]
No, I mean, the failures should be cached as well. hatty_cat changed their username.

**Comment by confuser** [comment]
Failures can't be cached, as they may have failed due to rate limiting.

Have you successfully converted? I know some very large servers have been able to convert without any problems.

**Comment by gdude2002** [comment]
I eventually managed to convert, but I had to restart the process 8-9 times to convert the entire DB.

Also, sure, but afaik the API returns different results for each? I don't remember exactly, it's been a while since I've worked with it
