### ISSUE TITLE
Error occurred while enabling BanManager v5.0.0 (Is it up to date?) Caused by: java.sql.SQLException: Column 'id' not found.

### ISSUE THREAD

**Issue by JohOply** [BanManagement/BanManager#177]
Hi !

I follow instructions ( http://dev.bukkit.org/bukkit-plugins/ban-management/pages/uuid-update/ ) but there is an error at step 19

[22:12:03 INFO]: [BanManager] Enabling BanManager v5.0.0
[22:12:03 INFO]: [BanManager] Loaded 0 bans into memory
[22:12:03 INFO]: [BanManager] Loaded 0 mutes into memory
[22:12:03 ERROR]: Error occurred while enabling BanManager v5.0.0 (Is it up to date?)
java.lang.IllegalStateException: Could not get next result for class me.confuser.banmanager.data.IpBanData
at me.confuser.banmanager.ormlite.stmt.SelectIterator.next(SelectIterator.java:183) ~[?:?]
at me.confuser.banmanager.storage.IpBanStorage.<init>(IpBanStorage.java:39) ~[?:?]
at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:403) ~[?:?]
at me.confuser.banmanager.BanManager.onEnable(BanManager.java:90) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.sql.SQLException: Column 'id' not found.
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1144) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseResults.findColumn(JdbcDatabaseResults.java:90) ~[?:?]
at me.confuser.banmanager.ormlite.field.FieldType.resultToJava(FieldType.java:815) ~[?:?]
at me.confuser.banmanager.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:60) ~[?:?]
at me.confuser.banmanager.ormlite.stmt.SelectIterator.getCurrent(SelectIterator.java:270) ~[?:?]
at me.confuser.banmanager.ormlite.stmt.SelectIterator.nextThrow(SelectIterator.java:161) ~[?:?]
at me.confuser.banmanager.ormlite.stmt.SelectIterator.next(SelectIterator.java:173) ~[?:?]
... 14 more

**Comment by Kakifrucht** [comment]
You did not add the proper table names into the config.

**Comment by confuser** [comment]
Your table has the incorrect structure, specifically v4. Please read the update instructions carefully.
