### ISSUE TITLE
import throws an MysqlDataTruncation error.

### ISSUE THREAD

**Issue by HoaxIT** [BanManagement/BanManager#200]
```
[23:55:17 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@17e3bf3c: INSERT INTO `bm_
player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)                                         
[23:55:17 WARN]:        at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[23:55:17 WARN]:        at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[23:55:17 WARN]:        at me.confuser.banmanager.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[23:55:17 WARN]:        at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[23:55:17 WARN]:        at me.confuser.banmanager.commands.ImportCommand.importPlayers(ImportCommand.java:170)
[23:55:17 WARN]:        at me.confuser.banmanager.commands.ImportCommand.access$000(ImportCommand.java:23)
[23:55:17 WARN]:        at me.confuser.banmanager.commands.ImportCommand$1.run(ImportCommand.java:55)
[23:55:17 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[23:55:17 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[23:55:17 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:55:17 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:55:17 WARN]:        at java.lang.Thread.run(Thread.java:745)
[23:55:17 WARN]: Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'expires' at row 1
[23:55:17 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3591)
[23:55:17 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[23:55:17 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[23:55:17 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[23:55:17 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[23:55:17 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[23:55:17 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[23:55:17 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[23:55:17 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[23:55:17 WARN]:        at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[23:55:17 WARN]:        at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[23:55:17 WARN]:        ... 10 more
```

**Comment by confuser** [comment]
Any idea what the value of expires is? You shouldn't really be getting back a unix timestamp that's greater than 10 digits.

Can you provide your banned-players.json file please?

**Comment by fillefilip8** [comment]
I got this too.
I just installed BanManagement on my server and linked it up with mysql.
The tables is created just fine.
I cant ban anyone. Just getting errors

**Comment by confuser** [comment]
Lack of response. Closing.

Please re-comment with provided data as requested.
