### ISSUE TITLE
Banmanager is outputting wrong uuid sometimes.

### ISSUE THREAD

**Issue by tryy3** [BanManagement/BanManager#212]
Hi, I got a really weird problem with my server, for some people, ban manager is giving out the wrong UUID, it doesn't happen to all players, just some players.

When people join, I sometimes get this error message:

```
[03:24:02 INFO]: UUID of player tryyy3 is 1d3d4b2b-e4a8-47fd-b59c-0802043a7e56
[03:24:02 INFO]: tryyy3[/0.0.0.0:48795] logged in with entity id 34625 at ([plotworld] 2041.3417116285696, 70.0, 1710.0775757708407)
[03:24:02 INFO]: [GAListener] Player: tryyy3 has 0 votes
[03:24:02 INFO]: [BanManager] Requesting name for adc4c9dd-6d9e-3821-b289-c99d86509d2b
[03:24:02 WARN]: java.lang.Exception: Error retrieving name from https://api.mojang.com/user/profiles/adc4c9dd6d9e3821b289c99d86509d2b/names
[03:24:02 WARN]:        at me.confuser.banmanager.util.UUIDUtils.getCurrentName(UUIDUtils.java:108)
[03:24:02 WARN]:        at me.confuser.banmanager.storage.PlayerStorage.createOrUpdate(PlayerStorage.java:113)
[03:24:02 WARN]:        at me.confuser.banmanager.listeners.JoinListener$1.run(JoinListener.java:100)
[03:24:02 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[03:24:02 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[03:24:02 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[03:24:02 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[03:24:02 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

You can clearly see that when I log in, I have the UUID 1d3d4b2b-e4a8-47fd-b59c-0802043a7e56, but then ban manager is trying to get the names of the UUID adc4c9dd6d9e3821b289c99d86509d2b.
I have tried to figure out why its giving me the wrong UUID but I am clueless.

I am running a bungeecord network, so the servers are running in offline mode, but I am using the latest build (Build 91 from jenkins) and I set the online mode setting to false in ban manager and it didn't change anything.

I hope you guys know what the issue is, because I have tried to find the cause of it, but I have no idea why ban manager thinks I got a different UUID, when its clearly giving out the correct one.

Oh and I have set bungeecord to true in spigot.yml so bungeecord should give out the correct uuid.

**Comment by confuser** [comment]
The UUID isn't wrong, the only reason BM will make a request like that when a player joins the server, is if it detects duplicate names in your database.

E.g. you must have tryyy3 already in your database but with a different uuid, meaning the current tryyy3 was taken by someone else who already has joined your server.

So the UUID it is looking up, is for the duplicate, not the player joining the server.
