### ISSUE TITLE
Issue when removing Ip bans

### ISSUE THREAD

**Issue by KasperFranz** [BanManagement/BanManager#230]
when running /unbanipall as the console.

[20:04:25 WARN]: Exception in thread "Craft Scheduler Thread - 141"
[20:04:25 WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.2.0 generated an exception while executing task 46783
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
        at me.confuser.banmanager.bukkitutil.Message.replace(Message.java:24)
        at me.confuser.banmanager.bukkitutil.Message.set(Message.java:30)
        at me.confuser.banmanager.commands.external.UnbanIpAllCommand$1.run(UnbanIpAllCommand.java:64)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by KasperFranz** [comment]
So i can just use the marven build and get it :)?

if i remember correct there was a issue with like 52 also :)
