### ISSUE TITLE
/bmexport missing JsonWriter for Spigot

### ISSUE THREAD

**Issue by MegaNarwhal** [BanManagement/BanManager#232]
Running Spigot git-Spigot-dbe012b-63e28b1, BanManager 5.3.0.

```
[03:21:17 INFO]: MegaNarwhal_ issued server command: /bmexport players
[03:21:17 WARN]: Exception in thread "Craft Scheduler Thread - 80"
[03:21:17 WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.3.0 generated an exception while executing task 411
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/com/google/gson/stream/JsonWriter
        at me.confuser.banmanager.commands.ExportCommand.exportPlayers(ExportCommand.java:141)
        at me.confuser.banmanager.commands.ExportCommand.access$000(ExportCommand.java:20)
        at me.confuser.banmanager.commands.ExportCommand$1.run(ExportCommand.java:54)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

From Spigot 1.8.3 announcement:
"For the developers out there there is one change that will affect a few NMS plugins and will be useful for Bukkit plugins. The Google Gson library has been moved out of org.bukkit.craftbukkit.libs and instead added to its normal location, as part of the Bukkit API. This means that plugins wishing to use Gson as an advanced JSON reading library may now do so without shading their own copy or using non-api methods."

http://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-1-8-3.53745/

**Comment by confuser** [comment]
Right, I'm getting fed up of the changes spigots are doing with package changes. They are making it incredibly difficult to make plugins backwards compatible.

Not only does that post fail to mention that it's 'normal' location is com.google.gson, but it's no longer within net.minecraft.util.com.google.gson nor org.bukkit.craftbukkit.libs.com.google.gson which is where 1.7.10 craftbukkit builds and below have it.

`This means that plugins wishing to use Gson as an advanced JSON reading library may now do so without shading their own copy`
Completely false, I'm either going to have to shade in my own copy for compatibility sake with different versions further increasing the built jar size of this plugin, or have to resort to reflection. This is getting rather ridiculous.

**Comment by MegaNarwhal** [comment]
Yup.
```
[20:08:23 INFO]: MegaNarwhal_ issued server command: /bmimport player
[20:08:23 INFO]: [BanManager] §aPlayer ban import started
[20:08:23 WARN]: Exception in thread "Craft Scheduler Thread - 0"
[20:08:23 WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.3.0 generated an exception while executing task 23
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/com/google/gson/stream/JsonReader
        at me.confuser.banmanager.commands.ImportCommand.importPlayers(ImportCommand.java:79)
        at me.confuser.banmanager.commands.ImportCommand.access$000(ImportCommand.java:23)
        at me.confuser.banmanager.commands.ImportCommand$1.run(ImportCommand.java:55)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more
```
