### ISSUE TITLE
Problems with banall

### ISSUE THREAD

**Issue by KasperFranz** [BanManagement/BanManager#234]
I'm not totally sure why this issues comes.

[03:28:58 INFO]: <playername> has been permanently banned by <banned_by> <for>

[03:28:58 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@7de36ed7: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)
[03:28:58 WARN]:        at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[03:28:58 WARN]:        at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[03:28:58 WARN]:        at me.confuser.banmanager.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[03:28:58 WARN]:        at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[03:28:58 WARN]:        at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:109)
[03:28:58 WARN]:        at me.confuser.banmanager.runnables.ExternalBanSync.newBans(ExternalBanSync.java:70)
[03:28:58 WARN]:        at me.confuser.banmanager.runnables.ExternalBanSync.run(ExternalBanSync.java:37)
[03:28:58 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[03:28:58 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[03:28:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[03:28:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[03:28:58 WARN]:        at java.lang.Thread.run(Thread.java:744)
[03:28:58 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'P\xE5$\xA0\x05[H\xDA\x87-B N6G\x19' for key 'bm_player_bans_player_idx'
[03:28:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:28:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[03:28:58 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:28:58 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[03:28:58 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:28:58 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[03:28:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[03:28:58 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[03:28:58 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[03:28:58 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[03:28:58 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[03:28:58 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[03:28:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[03:28:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[03:28:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[03:28:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[03:28:58 WARN]:        at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[03:28:58 WARN]:        at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[03:28:58 WARN]:        ... 10 more

**Comment by confuser** [comment]
That issue should be fixed in v5.3

**Comment by KasperFranz** [comment]
Ok good :) 
This might have been on 5.2, we are gonna update soon then, thank you for your reply :)
