### ISSUE TITLE
player not found

### ISSUE THREAD

**Issue by JohOply** [BanManagement/BanManager#240]
Hi

I have updated BanManager recently from 4.0 to 5.3.0. There was some problem during updating (plugin can't import a part of bans from the older version), but i don't think there is a link with today's bug.

So, today i want ban a player. Nice, i use /ban, that's work. Later, i want to use bminfo for this player, but that doesn't work. ( "player not found, are you sure they exist ?" )
You can see here : http://img11.hostingpics.net/pics/87938020150425160947.png

Later, i want to ban a player for grief, but i can't for the same reason.. For another, i can't ban his IP address..

Could you help me please?

NB : Sorry if my english isn't correct, isn't my native language. Thanks

EDIT: Also, there isn't any message when i use /unbanip if ip is really unbanned

**Comment by confuser** [comment]
Check your console for errors.

**Comment by JohOply** [comment]
I havn't got an error each time, but i have found one, at least : 

[16:00:13 INFO]: [BanManager] Requesting UUIDs for BadDemmon
[16:00:13 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerData@4bc4f743: INSERT INTO `bm_players` (`id` ,`name` ,`ip` ,`lastSeen` ) VALUES (?,?,?,?)
[16:00:13 WARN]: at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[16:00:13 WARN]: at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[16:00:13 WARN]: at me.confuser.banmanager.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[16:00:13 WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[16:00:13 WARN]: at me.confuser.banmanager.storage.PlayerStorage.retrieve(PlayerStorage.java:194)
[16:00:13 WARN]: at me.confuser.banmanager.commands.BanCommand$1.run(BanCommand.java:94)
[16:00:13 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[16:00:13 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[16:00:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[16:00:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[16:00:13 WARN]: at java.lang.Thread.run(Thread.java:744)
[16:00:13 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'ç&Z9=‘9&\*Ä' for key 'PRIMARY'
[16:00:13 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:00:13 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[16:00:13 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:00:13 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[16:00:13 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[16:00:13 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:382)
[16:00:13 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[16:00:13 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[16:00:13 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[16:00:13 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[16:00:13 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[16:00:13 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[16:00:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[16:00:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[16:00:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[16:00:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[16:00:13 WARN]: at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[16:00:13 WARN]: at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[16:00:13 WARN]: ... 9 more

**Comment by confuser** [comment]
Are you running in offline mode?

**Comment by JohOply** [comment]
Yes sir

**Comment by confuser** [comment]
Please update to builds 112 or higher, they contain a fix for case sensitivity issues with offline mode servers

http://ci.frostcast.net/job/BanManager/
