### ISSUE TITLE
Player not found... Round 2 !

### ISSUE THREAD

**Issue by JohOply** [BanManagement/BanManager#245]
Hi !

This ticket is following one : https://github.com/BanManagement/BanManager/issues/240
I uploaded BanManager v5.4.0 build 117 on my 1.7.10 Offline Spigot Server (in config too)

But the problem seems stay here... On this screen, you can see a player who was banned, but i can't use /bminfo command... : http://i.snag.gy/PBxpW.jpg

Error log : 

[22:57:54 INFO]: [BanManager] Requesting name for 61948848-4e69-3e48-99e4-4fce8576f16f
[22:57:54 WARN]: java.lang.Exception: Error retrieving name from https://api.mojang.com/user/profiles/619488484e693e4899e44fce8576f16f/names
[22:57:54 WARN]: at me.confuser.banmanager.util.UUIDUtils.getCurrentName(UUIDUtils.java:108)
[22:57:54 WARN]: at me.confuser.banmanager.storage.PlayerStorage.createOrUpdate(PlayerStorage.java:137)
[22:57:54 WARN]: at me.confuser.banmanager.listeners.JoinListener.onJoin(JoinListener.java:111)
[22:57:54 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:57:54 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[22:57:54 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:57:54 WARN]: at java.lang.reflect.Method.invoke(Method.java:606)
[22:57:54 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
[22:57:54 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:57:54 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509)
[22:57:54 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:491)
[22:57:54 WARN]: at net.minecraft.server.v1_7_R4.ThreadPlayerLookupUUID.fireLoginEvents(ThreadPlayerLookupUUID.java:79)
[22:57:54 WARN]: at net.minecraft.server.v1_7_R4.ThreadPlayerLookupUUID.run(ThreadPlayerLookupUUID.java:32)

If i miss something, please tell me what

Have a nice day !

**Comment by confuser** [comment]
If you are running in true offline mode, ensure your config.yml node onlineMode is set to false.

BanManager will otherwise assume it is in online mode and request names from Mojang
