### ISSUE TITLE
A warning console

### ISSUE THREAD

**Issue by Max633** [BanManagement/BanManager#246]
Hi

[11:50:03 WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.IpBanData
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
[11:50:03 WARN]: at me.confuser.banmanager.storage.IpBanStorage.findBans(IpBanStorage.java:136)
[11:50:03 WARN]: at me.confuser.banmanager.runnables.IpSync.newBans(IpSync.java:48)
[11:50:03 WARN]: at me.confuser.banmanager.runnables.IpSync.run(IpSync.java:29)
[11:50:03 WARN]: at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
[11:50:03 WARN]: at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[11:50:03 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[11:50:03 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[11:50:03 WARN]: at java.lang.Thread.run(Thread.java:744)
[11:50:03 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'created' in 'where clause'
[11:50:03 WARN]: at sun.reflect.GeneratedConstructorAccessor154.newInstance(Unknown Source)
[11:50:03 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:50:03 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[11:50:03 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[11:50:03 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:382)
[11:50:03 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[11:50:03 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[11:50:03 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[11:50:03 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[11:50:03 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[11:50:03 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[11:50:03 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[11:50:03 WARN]: at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:55)
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55)
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:247)
[11:50:03 WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
[11:50:03 WARN]: ... 11 more

Thank you for help

**Comment by confuser** [comment]
`unknown column 'created'`

The data structure is incorrect. I assume you updated from v4 but did not follow the conversion instructions.

http://dev.bukkit.org/bukkit-plugins/ban-management/pages/uuid-update/
