### ISSUE TITLE
Exception at command

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#276]
git-Spigot-2ec6f06-7722428 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
BM obviously v5.4.1

```
[19:55:14 INFO]: Olaf issued server command: /warp
[19:55:14 WARN]: Exception in thread "Craft Scheduler Thread - 590"
[19:55:14 WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.4.1 generated an exception while executing task 33
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Errors getting more results of class me.confuser.banmanager.data.PlayerBanData
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:103)
        at me.confuser.banmanager.runnables.BanSync.newBans(BanSync.java:52)
        at me.confuser.banmanager.runnables.BanSync.run(BanSync.java:31)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
        at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
        at com.mysql.jdbc.ResultSetImpl.first(ResultSetImpl.java:1164)
        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseResults.first(JdbcDatabaseResults.java:58)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:79)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
        ... 7 more
```

Trying /warp again didn't  generate the same message. Well I have no clue if this is related to /warp at all...

**Comment by Kakifrucht** [comment]
I'm pretty sure the command is just a coincidence :D

**Comment by confuser** [comment]
Command is a coincidence. It's an issue with the BanSync, looks like the cursor was closed for some reason. Have you had any other database issues or exceptions?

**Comment by EvilOlaf** [comment]
Nope. Everything runs fine and well.

**Comment by confuser** [comment]
Did you use /bmsync?

**Comment by EvilOlaf** [comment]
Never used that command.

**Comment by confuser** [comment]
Please re-open if you notice this issue again with the latest developer build.
