### ISSUE TITLE
Issue with backward compatibility

### ISSUE THREAD

**Issue by kazimir** [BanManagement/BanManager#277]
Hey,

I got an issue with backward compatibility of version 5 (trusting bukkitdevs game versions on the download page).

I'm currently running *Cauldron-MCPC-Plus version git-Cauldron-MCPC-Plus1.6.4-1.965.21.89 (MC: 1.6.4) (Implementing API version 1.6.4-R2.1-SNAPSHOT)*

The UUID methods are not implemented in 1.6.4 and so I get a *NoSuchMethodError* when calling this methods. Is there any way to solve this?

This is the error I get:

```
2015-05-17 22:00:25 [SEVERE] Could not pass event AsyncPlayerPreLoginEvent to BanManager v5.4.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:437)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:461)
        at net.minecraft.network.ThreadLoginVerifier.run(ThreadLoginVerifier.java:69)
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.AsyncPlayerPreLoginEvent.getUniqueId()Ljava/util/UUID;
        at me.confuser.banmanager.listeners.JoinListener.onJoin(JoinListener.java:139)
        at sun.reflect.GeneratedMethodAccessor262.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:435)
        ... 5 more
```

Thanks in advance!
kazimir

**Comment by confuser** [comment]
You're right, for some reason I thought 1.6.4 supported the uuid methods. I've removed 1.6.4 from BukkitDev as a listed compatible version.

v4 should function fine for you, but be aware it doesn't support uuids and name changes will bypass the bans.
