### ISSUE TITLE
Undefined methods

### ISSUE THREAD

**Issue by SlimaKCoder** [BanManagement/BanManager#278]
Error when starting plugin:
```
[18:19:00 INFO]: [BanManager] Enabling BanManager v5.5.0-SNAPSHOT
[18:19:00 ERROR]: Error occurred while enabling BanManager v5.5.0-SNAPSHOT (Is it up to date?)
java.lang.Error: Unresolved compilation problems:
        The method isDebugEnabled() is undefined for the type DefaultConfig
        The method getPlayerStorage() is undefined for the type BanManager

        at me.confuser.banmanager.BanManager.onEnable(BanManager.java:110) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-5818108-5e91446]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-5818108-5e91446]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-5818108-5e91446]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-5818108-5e91446]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-5818108-5e91446]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot.jar:git-Spigot-5818108-5e91446]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-5818108-5e91446]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-5818108-5e91446]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-5818108-5e91446]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-5818108-5e91446]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
```
I use latest Spigot 1.8.4:
```
[18:19:15 INFO]: This server is running CraftBukkit version git-Spigot-5818108-5e91446 (MC: 1.8.4) (Implementing API version 1.8.4-R0.1-SNAPSHOT)
[18:19:15 INFO]: Checking version, please wait...
[18:19:17 INFO]: You are running the latest version
```
And latest plugin compiled from source code, commit: https://github.com/BanManagement/BanManager/commit/d8305308d7addb2943ffe69506f6ea70fb7fbbc6:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder with a thread count of 4
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building BanManager 5.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ BanManager ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources to .
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ BanManager ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ BanManager ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\SlimaK\git\BanManager\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ BanManager ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ BanManager ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ BanManager ---
[INFO] Building jar: C:\Users\SlimaK\git\BanManager\target\BanManager.jar
[INFO] 
[INFO] --- maven-shade-plugin:2.3:shade (default) @ BanManager ---
[INFO] Including com.sk89q:guavabackport:jar:1.1 in the shaded jar.
[INFO] Including com.j256.ormlite:ormlite-core:jar:4.48 in the shaded jar.
[INFO] Including com.j256.ormlite:ormlite-jdbc:jar:4.48 in the shaded jar.
[INFO] Including org.mcstats.bukkit:metrics-lite:jar:R6 in the shaded jar.
[INFO] Including me.confuser:BukkitPluginUtil:jar:1.5.3 in the shaded jar.
[INFO] Including com.googlecode.concurrent-trees:concurrent-trees:jar:2.4.0 in the shaded jar.
[INFO] Including net.gravitydevelopment.updater:updater:jar:2.3 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.3.1 in the shaded jar.
[INFO] Including commons-net:commons-net:jar:3.3 in the shaded jar.
[INFO] Including com.github.spullara.cli-parser:cli-parser:jar:1.1.2 in the shaded jar.
[INFO] Minimizing jar me.confuser:BanManager:jar:5.5.0-SNAPSHOT
[INFO] Minimized 1031 -> 432 (41%)
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing C:\Users\SlimaK\git\BanManager\target\BanManager.jar with C:\Users\SlimaK\git\BanManager\target\BanManager-5.5.0-SNAPSHOT-shaded.jar
[INFO] Dependency-reduced POM written at: C:\Users\SlimaK\git\BanManager\dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.216 s (Wall Clock)
[INFO] Finished at: 2015-05-20T17:31:38+01:00
[INFO] Final Memory: 11M/233M
[INFO] ------------------------------------------------------------------------
```

**Comment by confuser** [comment]
If you're having problems compiling the plugin yourself, try downloading from the CI server instead, it automatically updates after every commit.

http://ci.frostcast.net/job/BanManager/

**Comment by SlimaKCoder** [comment]
Which Java version do you use for compiling?
