### ISSUE TITLE
BanManager mysql error

### ISSUE THREAD

**Issue by KreWw** [BanManagement/BanManager#280]
Still this error persists. I cant seem to fix it!! Please help me! Using v5.4.1
Please dont say stuff that wont actually help.

```
[13:41:16] [Server thread/INFO]: Fanikz issued server command: /unbanall ChocolateTimbit Testing purpose
[13:41:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'unbanall' in plugin BanManager v5.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at me.confuser.banmanager.bukkitutil.Message.replace(Message.java:24) ~[?:?]
	at me.confuser.banmanager.bukkitutil.Message.set(Message.java:30) ~[?:?]
	at me.confuser.banmanager.commands.external.UnbanAllCommand.onCommand(UnbanAllCommand.java:41) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	... 15 more




[13:41:17] [Server thread/INFO]: Fanikz issued server command: /unbanall ChocolateTimbit Testing purpose
[13:41:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'unbanall' in plugin BanManager v5.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at me.confuser.banmanager.bukkitutil.Message.replace(Message.java:24) ~[?:?]
	at me.confuser.banmanager.bukkitutil.Message.set(Message.java:30) ~[?:?]
	at me.confuser.banmanager.commands.external.UnbanAllCommand.onCommand(UnbanAllCommand.java:41) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	... 15 more
[13:41:17] [Server thread/INFO]: Fanikz issued server command: /unbanall ChocolateTimbit Testing purpose
[13:41:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'unbanall' in plugin BanManager v5.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at me.confuser.banmanager.bukkitutil.Message.replace(Message.java:24) ~[?:?]
	at me.confuser.banmanager.bukkitutil.Message.set(Message.java:30) ~[?:?]
	at me.confuser.banmanager.commands.external.UnbanAllCommand.onCommand(UnbanAllCommand.java:41) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	... 15 more
[13:41:17] [Server thread/INFO]: Fanikz issued server command: /unbanall ChocolateTimbit Testing purpose
[13:41:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'unbanall' in plugin BanManager v5.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at me.confuser.banmanager.bukkitutil.Message.replace(Message.java:24) ~[?:?]
	at me.confuser.banmanager.bukkitutil.Message.set(Message.java:30) ~[?:?]
	at me.confuser.banmanager.commands.external.UnbanAllCommand.onCommand(UnbanAllCommand.java:41) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
	... 15 more
```

**Comment by confuser** [comment]
This has already been fixed

http://ci.frostcast.net/job/BanManager/136/
