### ISSUE TITLE
Using time parameter at bminfo causes Exception

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#310]
```
[11:27:53 INFO]: Olaf issued server command: /bminfo bad_user -t
[11:27:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bminfo' in plugin BanManager v5.6.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Must have a value for non-boolean argument
        at me.confuser.banmanager.internal.cli.Args.consumeArgumentValue(Args.java:358) ~[?:?]
        at me.confuser.banmanager.internal.cli.Args.processField(Args.java:113) ~[?:?]
        at me.confuser.banmanager.internal.cli.Args.parse(Args.java:83) ~[?:?]
        at me.confuser.banmanager.util.InfoCommandParser.<init>(InfoCommandParser.java:40) ~[?:?]
        at me.confuser.banmanager.commands.InfoCommand.onCommand(InfoCommand.java:34) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
        ... 15 more
```

**Comment by EvilOlaf** [comment]
It is obvious but I should have mentioned that this happens only if I use the `-t` parameter WITHOUT argument.
