### ISSUE TITLE
Can´t get name from mojang

### ISSUE THREAD

**Issue by Paktosan** [BanManagement/BanManager#312]
When a player connects to a leaf of my bungeecord network, I get the following error:
```
[16:37:33] [Thread-21/INFO]: [BanManager] Requesting name for a9580647-7fcc-370f-98f1-052f48892060
[16:37:33] [Thread-21/WARN]: java.lang.Exception: Error retrieving name from https://api.mojang.com/user/profiles/a95806477fcc370f98f1052f48892060/names
[16:37:33] [Thread-21/WARN]: 	at me.confuser.banmanager.util.UUIDUtils.getCurrentName(UUIDUtils.java:105)
[16:37:33] [Thread-21/WARN]: 	at me.confuser.banmanager.storage.PlayerStorage.createOrUpdate(PlayerStorage.java:82)
[16:37:33] [Thread-21/WARN]: 	at me.confuser.banmanager.listeners.JoinListener.banCheck(JoinListener.java:29)
[16:37:33] [Thread-21/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:37:33] [Thread-21/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[16:37:33] [Thread-21/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:37:33] [Thread-21/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[16:37:33] [Thread-21/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:37:33] [Thread-21/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:37:33] [Thread-21/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:37:33] [Thread-21/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[16:37:33] [Thread-21/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248)
[16:37:33] [Thread-21/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:172)
[16:37:33] [Thread-21/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:37:33] [Thread-21/INFO]: UUID of player Paktosan is 0bac71ad-9156-487e-9ade-9c5b57274b23
````
Please notice that BanManager wants to use a different UUID than I actually have. How can we fix this?
Currently v5 is installed

**Comment by confuser** [comment]
Update to v5.5 and the message will be more clear.

The reason the UUID is different, is because BanManager has detected that the player who just joined, has the same name as a player with a different UUID. It is trying to update its records by contacting Mojang to find out what the name of the other player is.
