### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by dako98** [BanManagement/BanManager#313]
[21:07:15] [Server thread/INFO]: [BanManager] Enabling BanManager v5.4.1
[21:07:22] [Server thread/INFO]: [BanManager] Loaded 0 bans into memory
[21:07:23] [Server thread/INFO]: [BanManager] Loaded 0 mutes into memory
[21:07:24] [Server thread/INFO]: [BanManager] Loaded 0 ip bans into memory
[21:07:25] [Server thread/INFO]: [BanManager] Loaded 0 ip range bans into memory
[21:07:26] [Server thread/ERROR]: [BanManager] The time on your server and MySQL database are out by 33 seconds, this may cause syncing issues.

[21:08:38] [pool-3-thread-5/WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.IpBanData
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.storage.IpBanStorage.findBans(IpBanStorage.java:136)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.runnables.IpSync.newBans(IpSync.java:48)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.runnables.IpSync.run(IpSync.java:29)
[21:08:38] [pool-3-thread-5/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
[21:08:38] [pool-3-thread-5/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:08:38] [pool-3-thread-5/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[21:08:38] [pool-3-thread-5/WARN]: 	at java.sql.DriverManager.getConnection(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at java.sql.DriverManager.getConnection(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:252)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:136)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
[21:08:38] [pool-3-thread-5/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
[21:08:38] [pool-3-thread-5/WARN]: 	... 11 more
[21:08:38] [pool-3-thread-5/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: User dako98_bansAdmin already has more than 'max_user_connections' active connections
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
[21:08:38] [pool-3-thread-5/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186)
[21:08:38] [pool-3-thread-5/WARN]: 	... 28 more

The config has the right details and it was able to connect and create the table at the first startup. The MySQL server has remote connection and the user has full permissions.

**Comment by confuser** [comment]
A few things
> [21:07:26] [Server thread/ERROR]: [BanManager] The time on your server and MySQL database are out by 33 seconds, this may cause syncing issues.

> [21:08:38] [pool-3-thread-5/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
The connection was lost and it wasn't able to reconnect. If you're using a remote connection, ensure it is stable.

**Comment by EvilOlaf** [comment]
Just to get a bit more in detail: 
Either blame your Minecraft server host or database server host or both to do their job properly set their server time using the `ntpd` correctly.

It is important for each and every network activity that the time is set correctly at both sending and receiving partner.

**Comment by dako98** [comment]
I host the server. The database host is helihost. I do not lose connection
nor does the database. I get the same error if I use warn, ban, kick.
На 26.06.2015 08:59 "Very Evil Olaf" <notifications@github.com> написа:

**Comment by frdmn** [comment]
@dako98 do you have the option to setup the MySQL server on the same machine as the MC server, so you dont need to rely on external connections?
