### ISSUE TITLE
Mysql database not connecting

### ISSUE THREAD

**Issue by pricey123** [BanManagement/BanManager#314]
I have entered all the correct details and have changed the ip, but the plugin keeps trying to connect to 127.0.0.1 instead of the ip i am entering.

**Comment by pricey123** [comment]
[16:04:37] [Server thread/INFO]: [BanManager] Enabling BanManager v5.5.0
[16:04:57] [Server thread/WARN]: [BanManager] An error occurred attempting to make a database connection, please see stack trace below
[16:04:57] [Server thread/INFO]: [BanManager] Disabling BanManager v5.5.0
[16:04:57] [Server thread/INFO]: 2015-06-27 16:04:57,684 [DEBUG] JdbcPooledConnectionSource closing
[16:04:57] [Server thread/INFO]: 2015-06-27 16:04:57,685 [DEBUG] JdbcPooledConnectionSource closing
[16:04:57] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
[16:04:57] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:04:57] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:04:57] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:04:57] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[16:04:57] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:04:57] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:04:57] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:04:57] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[16:04:57] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[16:04:57] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
[16:04:57] [Server thread/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:252)
[16:04:57] [Server thread/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:136)
[16:04:57] [Server thread/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111)
[16:04:57] [Server thread/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.isTableExists(BaseDaoImpl.java:689)
[16:04:57] [Server thread/WARN]: 	at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:42)
[16:04:57] [Server thread/WARN]: 	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:397)
[16:04:57] [Server thread/WARN]: 	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:120)
[16:04:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:04:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:04:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:04:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[16:04:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[16:04:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
[16:04:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
[16:04:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
[16:04:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
[16:04:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
[16:04:57] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:04:57] [Server thread/WARN]: Caused by: java.sql.SQLException: Access denied for user 'banmanager'@'lvmc1.netherbyte.com' (using password: YES)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
[16:04:57] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186)
[16:04:57] [Server thread/WARN]: 	... 30 more

I am not trying to connect to the database that is shown in the error. I have entered a different ip in the config.

**Comment by confuser** [comment]
http://dev.bukkit.org/bukkit-plugins/ban-management/#w-faq
