### ISSUE TITLE
Not Up To Date

### ISSUE THREAD

**Issue by niels1189** [BanManagement/BanManager#330]
[20:28:01] [Server thread/ERROR]: Error occurred while enabling BanManager v5.6.0 (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.storage.PlayerBanStorage.<init>(PlayerBanStorage.java:49) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:405) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:125) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot_1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_51]

Is the error I keep getting. I tried 5.6.0 (from dev.bukkit) and 5.6.1-SNAPSHOT (from jenkins)
Need this fixed as soon as possible.

want to point out this was working before I went on vacation. (1.5 weeks ago)

**Comment by confuser** [comment]
You have a data integrity issue with your database. Players table is missing the uuid for a particular ban. This is not a problem of the plugin itself.

**Comment by niels1189** [comment]
I'm unable to locate the table that's missing an uuid value.
I looked in all tables but none of them seem to have a null value for uuid.

**Comment by confuser** [comment]
None of them will be null. The problem is that you have a UUID in your ban table that does not exist in your players table.

**Comment by niels1189** [comment]
DELETE FROM bm_player_bans 
 WHERE NOT EXISTS(SELECT NULL
                    FROM bm_players
                   WHERE bm_players.id = player_id)

This query was used on the database and 1 row was deleted.
(Query posted for anyone else that has this issue)

**Comment by Maescool** [comment]
@niels1189 that query did fix it for me
