### ISSUE TITLE
AnotherException

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#349]
First command throw an exception, second time it was successful:
```
[08:55:47 INFO]: Olaf issued server command: /ban bad_player a reason
[08:55:47 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
[08:55:47 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:55:47 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:55:47 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:55:47 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[08:55:47 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[08:55:47 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[08:55:47 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[08:55:47 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[08:55:47 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[08:55:47 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[08:55:47 WARN]:        at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1213)
[08:55:47 WARN]:        at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1200)
[08:55:47 WARN]:        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4203)
[08:55:47 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:273)
[08:55:47 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:201)
[08:55:47 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedQueryForId.execute(MappedQueryForId.java:38)
[08:55:47 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.queryForId(StatementExecutor.java:85)
[08:55:47 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.queryForId(BaseDaoImpl.java:223)
[08:55:47 WARN]:        at me.confuser.banmanager.commands.BanCommand$1.run(BanCommand.java:119)
[08:55:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[08:55:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[08:55:47 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[08:55:47 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[08:55:47 WARN]:        at java.lang.Thread.run(Thread.java:745)
[08:55:56 INFO]: Olaf issued server command: /ban bad_player a reason
[08:55:56 INFO]: bad_player has been banned by Olaf.
```

I am not sure if this is related to an existing issue, so feel free to close this one if so.
v5.6.1

**Comment by confuser** [comment]
Yep, related to #321
