### ISSUE TITLE
Bungeecord | Are you sure they exist?

### ISSUE THREAD

**Issue by Jackiedk100** [BanManagement/BanManager#354]
Hello, my server is connected to a bungeecord server, and offline mode because that.
I maybe think thats why I get "Are you sure they exit", but how can I fix this problem?

This is my console
[21:10:45] [Server thread/INFO]: Jackiedk100 issued server command: /warn Smackeroonies test
[21:10:45] [Craft Scheduler Thread - 85/INFO]: [BanManager] Requesting UUIDs for Smackeroonies
[21:10:45] [Craft Scheduler Thread - 85/WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerData@5f0713ad: INSERT INTO `bm_players` (`id` ,`name` ,`ip` ,`lastSeen` ) VALUES (?,?,?,?)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at me.confuser.banmanager.storage.PlayerStorage.retrieve(PlayerStorage.java:163)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at me.confuser.banmanager.commands.WarnCommand$1.run(WarnCommand.java:88)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '\xAAl\xA5q\x81\x98B\x8E\x99\xDC\xC9\xD3K\x9D\xBCE' for key 'PRIMARY'
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[21:10:45] [Craft Scheduler Thread - 85/WARN]: 	... 9 more

**Comment by confuser** [comment]
Try the latest developer build http://ci.frostcast.net

**Comment by Jackiedk100** [comment]
When I try that, the web not working. I mean, many bugs.
Ex. If i search on a user, then his skin wont come up, and if he are banned, then nothing would stand there.

**Comment by confuser** [comment]
Please report website bugs over at https://github.com/BanManagement/BanManager-WebUI this repository is for the Java plugin.

**Comment by Jackiedk100** [comment]
You said I shall use the last developer build, but on the site, there is standing
Web interface is NOT compatible
