### ISSUE TITLE
Exception when banning player

### ISSUE THREAD

**Issue by CharlesVien** [BanManagement/BanManager#358]
```
[18:14:21 INFO]: An error occured whilst attempting to perform that command. Please check the console for the error
[18:14:21 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@950070f: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)
[18:14:21 WARN]:        at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[18:14:21 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[18:14:21 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[18:14:21 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[18:14:21 WARN]:        at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:111)
[18:14:21 WARN]:        at me.confuser.banmanager.commands.BanCommand$1.run(BanCommand.java:153)
[18:14:21 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[18:14:21 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:14:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:14:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:14:21 WARN]:        at java.lang.Thread.run(Thread.java:745)
.¸' for key 'bm_player_bans_player_idx'dbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'aÀ`òxDŽÌ
[18:14:21 WARN]:        at sun.reflect.GeneratedConstructorAccessor69.newInstance(Unknown Source)
[18:14:21 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:14:21 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[18:14:21 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[18:14:21 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[18:14:21 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[18:14:21 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[18:14:21 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[18:14:21 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[18:14:21 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[18:14:21 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[18:14:21 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[18:14:21 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[18:14:21 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[18:14:21 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[18:14:21 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[18:14:21 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[18:14:21 WARN]:        ... 9 more
```

This exception is shown in console upon banning a player sometimes, and it does not ban them. They can log back in with no other exception thrown.

Running BM v5.6.0 with Spigot v1.7.10-ProtocolHack.
If you need more information, please let me know.

**Comment by confuser** [comment]
Please update to a developer build

http://ci.frostcast.net

**Comment by confuser** [comment]
Closing due to lack of response and assumption the reported issue is solved in a developer build
