### ISSUE TITLE
Error While Mute Ban etc.

### ISSUE THREAD

**Issue by logtainment** [BanManagement/BanManager#367]
[16:50:30 INFO]: logtainment issued server command: /warn Manu test
[16:50:30 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerWarnData@1e45f023: INSERT INTO `bm_player_warnings` (`player_id` ,`reason` ,`actor_id` ,`created` ,`expires` ,`read` ) VALUES (?,?,?,?,?,?)
[16:50:30 WARN]:        at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[16:50:30 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[16:50:30 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[16:50:30 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[16:50:30 WARN]:        at me.confuser.banmanager.storage.PlayerWarnStorage.addWarning(PlayerWarnStorage.java:50)
[16:50:30 WARN]:        at me.confuser.banmanager.commands.WarnCommand$1.run(WarnCommand.java:133)
[16:50:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[16:50:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[16:50:30 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:50:30 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:50:30 WARN]:        at java.lang.Thread.run(Thread.java:745)
[16:50:30 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'actor_id' cannot be null
[16:50:30 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:50:30 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:50:30 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:50:30 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[16:50:30 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[16:50:30 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[16:50:30 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[16:50:30 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[16:50:30 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[16:50:30 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[16:50:30 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[16:50:30 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[16:50:30 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[16:50:30 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[16:50:30 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[16:50:30 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[16:50:30 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[16:50:30 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[16:50:30 WARN]:        ... 9 more

**Comment by confuser** [comment]
Please ensure you are using the latest version of BanManager, currently released is v5.6.1
