### ISSUE TITLE
Error when server start

### ISSUE THREAD

**Issue by JohOply** [BanManagement/BanManager#384]
Hi !

I don't know why, i have an error and plugin don't work (i can't ban nobody) :

[02:15:07 INFO]: [BanManager] Enabling BanManager v5.6.1
[02:15:08 ERROR]: Error occurred while enabling BanManager v5.6.1 (Is it up to date?)
java.lang.NullPointerException
at me.confuser.banmanager.storage.PlayerBanStorage.<init>(PlayerBanStorage.java:49) ~[?:?]
at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:405) ~[?:?]
at me.confuser.banmanager.BanManager.onEnable(BanManager.java:125) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]

**Comment by btilm305** [comment]
happens to me all the time... you have a banned player whose uuid is NOT in your bm_players table

**Comment by JohOply** [comment]
mhhh... Any command work (mute, tempmute, ban...) even if player is in the table :(

If i use mute : /mute PLAYER reason, the answer me "/mute <player> <reason>", like if there isn't any argument... I really don't know why, because there is the same version on the server since 1 month !! :/

**Comment by confuser** [comment]
Update to a development build, it'll ignore the ban that's causing the
issue and allow banmanager to work

**Comment by JohOply** [comment]
That's work with #179 , thank you !
