### ISSUE TITLE
[Issue] using /ban <player> <reason> and /tempban <player> <timediff> <reason> output is the command usage

### ISSUE THREAD

**Issue by Legoman99573** [BanManagement/BanManager#388]
i tried banning a player on my server, but when i used the command /tempban SuicidalHoneyBun 1m Griefing, the output was /tempban <player> <timediff> <reason>. The player shows up in the database. Can you fix this in the next release.

**Comment by confuser** [comment]
Then Banmanager is not enabled please check your start up logs.

**Comment by Legoman99573** [comment]
it said it loaded everything, but when i use the command, i dont even get an error message

**Comment by Legoman99573** [comment]
i am using a bungee server if that is helpful

**Comment by Legoman99573** [comment]
i checked and restarted the server, ill post the log if that will be helpful

**Comment by Legoman99573** [comment]
it said player is not found, is it because i am using bungeecord and have online-mode set to false

**Comment by confuser** [comment]
Possibly. Ensure you have spigot.yml setup properly with bungee cord.

**Comment by Legoman99573** [comment]
it never loaded spigot.yml when i got bungeecord

**Comment by Legoman99573** [comment]
ok i get this message when i banned him. its in the logs

[15:05:54] [Server thread/INFO]: Legoman99573 issued server command: /ban SuicidalHoneyBun Griefing
[15:05:55] [Craft Scheduler Thread - 107/INFO]: [BanManager] Requesting UUIDs for SuicidalHoneyBun
[15:05:59] [Craft Scheduler Thread - 107/WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerData@1af3899: INSERT INTO `bm_players` (`id` ,`name` ,`ip` ,`lastSeen` ) VALUES (?,?,?,?)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at me.confuser.banmanager.storage.PlayerStorage.retrieve(PlayerStorage.java:163)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at me.confuser.banmanager.commands.BanCommand$1.run(BanCommand.java:102)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '\xAF\xD0\x8F\xED7\xCCK\xA6\xB7~\xAE)\x84\x01\xA0\xF2' for key 'PRIMARY'
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[15:05:59] [Craft Scheduler Thread - 107/WARN]: 	... 9 more

**Comment by confuser** [comment]
It's on each of your minecraft servers. Please read the installation
instructions for bungeecord in online mode on the spigot website.

**Comment by Legoman99573** [comment]
i switched onlinemode to false in the banmanager config and it worked. Thanks

**Comment by Legoman99573** [comment]
it just posted him as banned ;)

**Comment by Legoman99573** [comment]
now the website says the player isnt griefed. go here and click SuicidalHoneyBun. thegearmc.net/bans
