### ISSUE TITLE
/unmuteall command is broken

### ISSUE THREAD

**Issue by Affixes** [BanManagement/BanManager#408]
Trying to globally unmute a player puts out the following error:

```[13:19:41 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'unmuteall' in plugin BanManager v5.7.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at me.confuser.banmanager.bukkitutil.Message.replace(Message.java:24) ~[?:?]
        at me.confuser.banmanager.bukkitutil.Message.set(Message.java:30) ~[?:?]
        at me.confuser.banmanager.commands.external.UnmuteAllCommand.onCommand(UnmuteAllCommand.java:42) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
        ... 15 more```

(Better formatting: http://paste.affixes.io/enuwedawik.profile)

The same issue happens with the same error on the latest BukkitDev version. As for Spigot, we are running: git-Spigot-d2856ae-8f0f4ed (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

**Comment by confuser** [comment]
Available as a developer build at http://ci.frostcast.net/job/BanManager/

Please read the changes first as it may contain breaking changes
