### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by confuser** [BanManagement/BanManager#418]
Quite a lot of structural changes would be required:
- player ip
- ip banning
- ip range banning
- bminfo

**Comment by confuser** [comment]
http://dev.mysql.com/doc/refman/5.6/en/miscellaneous-functions.html#function_inet6-aton

But requires MySQL 5.6.3 minimum and would also require converting from int columns to varbinary.

**Comment by paipai1997** [comment]
I got this error when a player joined server with ipv6 address.

> Caused by: java.lang.NumberFormatException: For input string: "2607:fea8:55f:f634:69eb:1985:a10:6228"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_111]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_111]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_111]
        at me.confuser.banmanager.util.IPUtils.toLong(IPUtils.java:22) ~[?:?]
        at me.confuser.banmanager.util.IPUtils.toLong(IPUtils.java:29) ~[?:?]
        at me.confuser.banmanager.data.PlayerData.<init>(PlayerData.java:61) ~[?:?]
        at me.confuser.banmanager.listeners.JoinListener.onJoin(JoinListener.java:193) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]

it looks like the plugin doesn't recognize the ipv6 address.

**Comment by EvilOlaf** [comment]
That's why this feature report is still open ;).

**Comment by Sulort** [comment]
would there be a solution in the foreseeable future?
could you pls fix it, that woul be very nice.

[23:17:34] [User Authenticator #1/ERROR]: Could not pass event AsyncPlayerPreLoginEvent to BanManager v7.0.0-SNAPSHOT
java.lang.NumberFormatException: For input string: "2003:c2:970c:bb00:9067:8ebb:6d87:d9cb%0"
