### ISSUE TITLE
Error last version.

### ISSUE THREAD

**Issue by NexGenHD** [BanManagement/BanManager#437]
Hello, I upgraded to the latest version and I'm getting this error, I've had in 2 servers that I have, the servers are offline and bukkit version 1.8.7.
anyone know what could be the problem?

[03:50:09] [Craft Scheduler Thread - 12/WARN]: java.lang.IllegalArgumentException: Unknown column name 'updated' in table bm_player_warnings
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at me.confuser.banmanager.internal.ormlite.table.TableInfo.getFieldTypeByColumnName(TableInfo.java:155)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.Where.findColumnFieldType(Where.java:681)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.Where.ge(Where.java:224)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at me.confuser.banmanager.storage.PlayerWarnStorage.findWarnings(PlayerWarnStorage.java:109)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at me.confuser.banmanager.runnables.WarningSync.newWarnings(WarningSync.java:31)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at me.confuser.banmanager.runnables.WarningSync.run(WarningSync.java:24)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[03:50:09] [Craft Scheduler Thread - 12/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by EvilOlaf** [comment]
Duplicate https://github.com/BanManagement/BanManager/issues/436
