### ISSUE TITLE
BM (5.7.2-SNAPSHOT210) spams the same error about database change on every start without realizing it's already done

### ISSUE THREAD

**Issue by rautamiekka** [BanManagement/BanManager#455]
I tested it by removing what it tries to add and it added it back, now just complaining every single time the Server is started, but everything works.

```
[15:03:34 INFO]: [BanManager] Enabling BanManager v5.7.2-SNAPSHOT
[15:03:35 INFO]: [BanManager] Loaded 2 bans into memory
[15:03:35 WARN]: java.sql.SQLException: Could not run raw execute statement ALTER TABLE bm_player_mutes ADD COLUMN `soft` TINYINT(1), ADD KEY `bm_player_mutes_soft_idx` (`soft`)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:606)
[15:03:35 WARN]:        at me.confuser.banmanager.storage.PlayerMuteStorage.<init>(PlayerMuteStorage.java:42)
[15:03:35 WARN]:        at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:395)
[15:03:35 WARN]:        at me.confuser.banmanager.BanManager.onEnable(BanManager.java:110)
[15:03:35 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:03:35 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:03:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:03:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[15:03:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[15:03:35 WARN]:        at java.lang.Thread.run(Thread.java:745)
[15:03:35 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'soft'
[15:03:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:03:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:03:35 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:03:35 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[15:03:35 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[15:03:35 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[15:03:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[15:03:35 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[15:03:35 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[15:03:35 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[15:03:35 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[15:03:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[15:03:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[15:03:35 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779)
[15:03:35 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.executeStatement(JdbcDatabaseConnection.java:122)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.executeRawNoArgs(StatementExecutor.java:420)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:604)
[15:03:35 WARN]:        ... 14 more
[15:03:35 INFO]: [BanManager] Loaded 0 mutes into memory
[15:03:35 WARN]: java.sql.SQLException: Could not run raw execute statement ALTER TABLE bm_player_mute_records ADD COLUMN `createdReason` VARCHAR(255),  ADD COLUMN `soft` TINYINT(1), ADD KEY `bm_player_mute_records_soft_idx` (`soft`)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:606)
[15:03:35 WARN]:        at me.confuser.banmanager.storage.PlayerMuteRecordStorage.<init>(PlayerMuteRecordStorage.java:33)
[15:03:35 WARN]:        at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:396)
[15:03:35 WARN]:        at me.confuser.banmanager.BanManager.onEnable(BanManager.java:110)
[15:03:35 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:03:35 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:03:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:03:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[15:03:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[15:03:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[15:03:35 WARN]:        at java.lang.Thread.run(Thread.java:745)
[15:03:35 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'createdReason'
[15:03:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:03:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:03:35 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:03:35 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[15:03:35 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[15:03:35 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[15:03:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[15:03:35 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[15:03:35 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[15:03:35 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[15:03:35 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[15:03:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[15:03:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[15:03:35 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779)
[15:03:35 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.executeStatement(JdbcDatabaseConnection.java:122)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.executeRawNoArgs(StatementExecutor.java:420)
[15:03:35 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:604)
[15:03:35 WARN]:        ... 14 more
[15:03:35 INFO]: [BanManager] Loaded 0 ip bans into memory
[15:03:35 INFO]: [BanManager] Loaded 0 ip range bans into memory
```

**Comment by confuser** [comment]
It's safe to ignore. Leaving this open so I don't forget to remove the stacktrace output.
