### ISSUE TITLE
Ban Manager can't connect to external database

### ISSUE THREAD

**Issue by JiNJaProductionz** [BanManagement/BanManager#457]
I am running Spigot version git-Spigot-5f38d38-12698ea (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT).

Right, so, when I fill in the external database part, this error comes up:
[22:19:44] [Server thread/INFO]: [BanManager] Loading BanManager v5.7.2-SNAPSHOT
[22:19:44] [Server thread/INFO]: [BanManager] Enabling BanManager v5.7.2-SNAPSHOT
[22:19:44] [Server thread/WARN]: [BanManager] Local Database is not enabled, disabling plugin
[22:19:44] [Server thread/INFO]: [BanManager] Disabling BanManager v5.7.2-SNAPSHOT

*By the way i'm not running a snapshot, I tried but didn't fix the problem, i'm using BanManager v5.7.1.

I've tried running it in the Local Database part, but this didn't fix it either.

[22:23:26] [Server thread/INFO]: [BanManager] Loading BanManager v5.7.2-SNAPSHOT
[22:23:26] [Server thread/INFO]: [BanManager] Enabling BanManager v5.7.2-SNAPSHOT
[22:23:44] [Server thread/WARN]: [BanManager] An error occurred attempting to make a database connection, please see stack trace below
[22:23:44] [Server thread/INFO]: [BanManager] Disabling BanManager v5.7.2-SNAPSHOT
[22:23:44] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
[22:23:44] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:23:44] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[22:23:44] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:23:44] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[22:23:44] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:23:44] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[22:23:44] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:23:44] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[22:23:44] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:571)
[22:23:44] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:187)
[22:23:44] [Server thread/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:252)
[22:23:44] [Server thread/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:136)
[22:23:44] [Server thread/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111)
[22:23:44] [Server thread/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.isTableExists(BaseDaoImpl.java:689)
[22:23:44] [Server thread/WARN]: 	at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:40)
[22:23:44] [Server thread/WARN]: 	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:392)
[22:23:44] [Server thread/WARN]: 	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:110)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:535)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:23:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[22:23:44] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[22:23:44] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[22:23:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[22:23:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:23:44] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[22:23:44] [Server thread/WARN]: 	at sun.reflect.GeneratedConstructorAccessor40.newInstance(Unknown Source)
[22:23:44] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:23:44] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186)
[22:23:44] [Server thread/WARN]: 	... 42 more
[22:23:44] [Server thread/WARN]: Caused by: java.net.ConnectException: Connection refused
[22:23:44] [Server thread/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[22:23:44] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
[22:23:44] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
[22:23:44] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
[22:23:44] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[22:23:44] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:579)
[22:23:44] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:528)
[22:23:44] [Server thread/WARN]: 	at java.net.Socket.<init>(Socket.java:425)
[22:23:44] [Server thread/WARN]: 	at java.net.Socket.<init>(Socket.java:241)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[22:23:44] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[22:23:44] [Server thread/WARN]: 	... 44 more

**Comment by confuser** [comment]
This isn't an issue with the plugin. It's saying it is unable to connect to the database. 

```
Connection refused
```

Please follow the FAQ at http://dev.bukkit.org/bukkit-plugins/ban-management/ if you're having problems allowing the minecraft server to connect to the database.

**Comment by JiNJaProductionz** [comment]
How are we supposed to use the plugin if we can't have/don't want a local database? For example, a host which does not offer databases?

**Comment by EvilOlaf** [comment]
"local" does not mean that the database has to run on the same machine as the minecraft server does. Since you can enter a hostname/IP-address this should have been obvious.

**Comment by JiNJaProductionz** [comment]
Think of it this way, it's more simple just to have one section, for a database. It would be much more simple than having two different sections.

**Comment by confuser** [comment]
The two different sections are quite clearly discussed and made apparent on the plugin page, under `Global/Multi-server support` over on BukkitDev. The majority of users seem to be able to understand the difference, but I will reiterate it here for anyone else who comes across this issue.

`local` in this context means the bans, mutes etc are `localised` to one particular server. The fact that all servers can have the same `local` database was merely a bonus based on the way I originally created the plugin.

**Comment by JiNJaProductionz** [comment]
So to have them synced, i'd need to setup two databases?

**Comment by confuser** [comment]
It entirely depends on how you want it to be synced. This is all mentioned on the BukkitDev homepage as stated in my previous comment. I urge you to go and read it.

When banning a player, if you want them to be banned on all servers, and this be applied for all bans, use the same local database and tables for all servers.

Want each server to have separate bans, but still want the ability to network ban, use different localised databases (or table names), but the same external database on all servers.

You can even take it a step further by having all servers with the same mutes, but different bans, and vice versa. BM was designed to be flexible.

**Comment by JiNJaProductionz** [comment]
Ok
