### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by Nico180902** [BanManagement/BanManager#518]
I was testing the plugin when I saw a error* in the console. I'm wondering because the plugin works fine and I really don't know why there is the failure
Version: v5.9.0 (SNAPSHOT)
Server Version: 1.8

``[12:58:04 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@1164624: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[12:58:04 WARN]: 	at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:119)
[12:58:04 WARN]: 	at me.confuser.banmanager.commands.TempBanCommand$1.run(TempBanCommand.java:153)
[12:58:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[12:58:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:58:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:58:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:58:04 WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:58:04 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '*\xDD\xD9\xBF,\xE9F\x03\xA7du\x94\xBC~\xD5r' for key 'bm_player_bans_player_idx'
[12:58:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:58:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[12:58:04 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[12:58:04 WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[12:58:04 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[12:58:04 INFO]: [BanHammer] airbus321 wurde von CONSOLE für 5 Minuten verbannt! Grund: Hacks Speedhack (Auto Detection)
[12:58:04 WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[12:58:04 WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[12:58:04 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[12:58:04 INFO]: [BanHammer] airbus321 wurde von CONSOLE für 5 Minuten verbannt! Grund: Hacks Speedhack (Auto Detection)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[12:58:04 INFO]: An error occured whilst attempting to perform that command. Please check the console for the error
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[12:58:04 WARN]: 	... 9 more
[12:58:04 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@4984ae10: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[12:58:04 WARN]: 	at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:119)
[12:58:04 WARN]: 	at me.confuser.banmanager.commands.TempBanCommand$1.run(TempBanCommand.java:153)
[12:58:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[12:58:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:58:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:58:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:58:04 WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:58:04 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '*\xDD\xD9\xBF,\xE9F\x03\xA7du\x94\xBC~\xD5r' for key 'bm_player_bans_player_idx'
[12:58:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:58:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[12:58:04 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[12:58:04 WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[12:58:04 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[12:58:04 WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[12:58:04 WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[12:58:04 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[12:58:04 WARN]: 	... 9 more
[12:58:04 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@5d56e60a: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[12:58:04 WARN]: 	at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:119)
[12:58:04 WARN]: 	at me.confuser.banmanager.commands.TempBanCommand$1.run(TempBanCommand.java:153)
[12:58:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[12:58:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:58:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:58:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:58:04 WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:58:04 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '*\xDD\xD9\xBF,\xE9F\x03\xA7du\x94\xBC~\xD5r' for key 'bm_player_bans_player_idx'
[12:58:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:58:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[12:58:04 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[12:58:04 WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[12:58:04 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[12:58:04 WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[12:58:04 WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[12:58:04 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[12:58:04 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[12:58:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[12:58:04 WARN]: 	at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[12:58:04 WARN]: 	... 9 `more`

**Comment by confuser** [comment]
Are you running in offline mode?

**Comment by Nico180902** [comment]
No Online

**Comment by Nico180902** [comment]
Another Information is, that I have got the failure all the 2 years I'm Ban Manager using (So in all Version I found the failure)

**Comment by confuser** [comment]
Can you provide a list of plugins you have installed please?

**Comment by Nico180902** [comment]
AntiAD
BanManager 
Chairs
ChatEX
ClearChat
Essentials
EssentialsSpawn
JoinMessage
MyCommand
NoCheatPlus
OPLock
Paintball
PEX
Suppysign
TimTheEnchanter
WorldEdit
WorldGuard

**Comment by Nico180902** [comment]
Update Now:
Now I almost can't ban someone, same error...

**Comment by confuser** [comment]
Are you running these commands via your console or as a player?

**Comment by Nico180902** [comment]
Ingame as Player, whx?

**Comment by Nico180902** [comment]
***why

**Comment by Nico180902** [comment]
Oh, or sometimes the Console, because I've linked BanManager with NoCheatPlus. That means, If NCP noticed, that someone has Hacks, he would banned by Console. Is this important for the error?

**Comment by confuser** [comment]
Perhaps, it may be related. However, all BM commands have checks to either unban an already banned player first if they have permission, or simply send an error message saying that the player is already banned.

The only other times I've seen this error occur is with offline mode servers, which BM doesn't support.

**Comment by confuser** [comment]
Unable to reproduce

**Comment by yoshee08** [comment]
I'm using this with bungeecord, which my default needs offline mode...how'm I supposed to use it while getting this error?

**Comment by confuser** [comment]
@yoshee08 As long as bungeecord is in online mode and forwarding UUIDs correctly, BM will function correctly.

**Comment by afroman84** [comment]
hello, i've seen this error first time in my bungeecord network.
my question is: could we simply remove a player from all the local database tables and treat him as a new player? because it seems that the INSERT in database fails because it finds a duplicate value for player id in the bm_player_bans table
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '=}X\x9F\x0D\xDFB\x1A\x9D'\xDB\xA5\xF5\xC4&]' for key 'bm5_player_bans_player_idx'
shouldn't a DELETE of the player from the db solve the issue?
