### ISSUE TITLE
placeholders sometimes not working

### ISSUE THREAD

**Issue by Twi5TeD** [BanManagement/BanManager#520]
https://gyazo.com/d6083d9853889e56c0e576f39f701ba5

**Comment by Twi5TeD** [comment]
also 

[10:15:57] [Server thread/INFO]: F64_Rx issued server command: /unmuteip Accumulating test
[10:15:57] [Craft Scheduler Thread - 37/WARN]: Exception in thread "Craft Scheduler Thread - 37" 
[10:15:57] [Craft Scheduler Thread - 37/WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.8.0 generated an exception while executing task 13234
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at me.confuser.banmanager.bukkitutil.Message.replace(Message.java:24)
	at me.confuser.banmanager.bukkitutil.Message.set(Message.java:30)
	at me.confuser.banmanager.commands.UnmuteIpCommand$1.run(UnmuteIpCommand.java:85)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by confuser** [comment]
Are you on the latest developer build?

**Comment by Twi5TeD** [comment]
im version 5.8.0

**Comment by confuser** [comment]
This should already be fixed in builds 41+

http://ci.frostcast.net/job/BanManager/

**Comment by Twi5TeD** [comment]
https://gyazo.com/5dce093a0e89ecb2fae3c8653dea25aa when i do muteip it does this

**Comment by Twi5TeD** [comment]
https://gyazo.com/4876c7e459b0a4761a38337fab386158

**Comment by Twi5TeD** [comment]
thanks

**Comment by Twi5TeD** [comment]
im using the latest dev build and this happens still
https://gyazo.com/14acf7488aa1567e49bad4d37c1847d9

**Comment by confuser** [comment]
Regenerate your messages.yml file. This only affects new users from v5.8.0.
