### ISSUE TITLE
ReportsLogger broken in 1.9

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#539]
`[22:43:35] [Craft Scheduler Thread - 1/WARN]: Exception in thread "Craft Scheduler Thread - 1" 
[22:43:35] [Craft Scheduler Thread - 1/WARN]: org.apache.commons.lang.UnhandledException: Plugin ReportsLogger v1.0.0-SNAPSHOT generated an exception while executing task 93
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at me.confuser.banmanager.internal.mcstats.MetricsLite.postPlugin(MetricsLite.java:285)
	at me.confuser.banmanager.internal.mcstats.MetricsLite.access$200(MetricsLite.java:51)
	at me.confuser.banmanager.internal.mcstats.MetricsLite$1.run(MetricsLite.java:173)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

**Comment by confuser** [comment]
This should really be in the ReportsLogger repo.
