### ISSUE TITLE
BanManager broken in 1.9

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#540]
`[22:44:01] [Craft Scheduler Thread - 12/WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.8.0 generated an exception while executing task 51
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at me.confuser.banmanager.internal.mcstats.MetricsLite.postPlugin(MetricsLite.java:285)
	at me.confuser.banmanager.internal.mcstats.MetricsLite.access$200(MetricsLite.java:51)
	at me.confuser.banmanager.internal.mcstats.MetricsLite$1.run(MetricsLite.java:173)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
`

**Comment by rautamiekka** [comment]
Once http://ci.frostcast.net/job/BanManager/ is online, try a dev version from there.

**Comment by confuser** [comment]
Metrics dependency just needs bumping. I believe there's a patching tool you can run BM through to avoid this issue until I get a chance to sort Jenkins out.
