### ISSUE TITLE
1.9 metrics error

### ISSUE THREAD

**Issue by Botanistt** [BanManagement/BanManager#545]
Using latest 1.9 spigot version. Receiving this error all the time:
`[20:20:19 WARN]: Exception in thread "Craft Scheduler Thread - 81"
[20:20:19 WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.8.0 generated an exception while executing task 368
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at me.confuser.banmanager.internal.mcstats.MetricsLite.postPlugin(MetricsLite.java:285)
        at me.confuser.banmanager.internal.mcstats.MetricsLite.access$200(MetricsLite.java:51)
        at me.confuser.banmanager.internal.mcstats.MetricsLite$1.run(MetricsLite.java:173)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
`
Please fix this, thank you!

**Comment by confuser** [comment]
This has already been fixed.

Either download a developer build (ensure you check for changes first) http://ci.frostcast.net/job/BanManager/ or run your existing .jar through the patch tool provided by SpigotMC within the 1.9 announcement.

**Comment by Botanistt** [comment]
I already downloaded latest one and I still get this. I will try to use spigot patch tool.
