### ISSUE TITLE
Connection not available, Request timed out? 

### ISSUE THREAD

**Issue by Tigatok** [BanManagement/BanManager#567]
[21:39:18 WARN]: java.lang.Exception: Apparent connection leak detected                                                                                                                                     │
[21:39:18 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)                                              │
[21:39:18 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)                                               │
[21:39:18 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)                                                                         │
[21:39:18 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:217)                                                                         │
[21:39:18 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:954)                                                                                     │
[21:39:18 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:484)                                                                                           │
[21:39:18 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:475)                                                                                           │
[21:39:18 WARN]:        at me.confuser.banmanager.storage.PlayerWarnStorage.findWarnings(PlayerWarnStorage.java:115)                                                                                        │
[21:39:18 WARN]:        at me.confuser.banmanager.runnables.WarningSync.newWarnings(WarningSync.java:31)                                                                                                    │
[21:39:18 WARN]:        at me.confuser.banmanager.runnables.WarningSync.run(WarningSync.java:24)                                                                                                            │
[21:39:18 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)                                                                                                                      │
[21:39:18 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)                                                                                                        │
[21:39:18 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)                                                                                              │
[21:39:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)                                                                                                  │
[21:39:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)                                                                                                  │
[21:39:18 WARN]:        at java.lang.Thread.run(Thread.java:745)                                                                                                                                            │
>                                                                 

Getting that spammed though the config and what not is set up correctly.

**Comment by xILukasIx** [comment]
This was already reported here and can be disabled in the newer dev builds:
https://github.com/BanManagement/BanManager/issues/547
[Dev Builds](http://dev.bukkit.org/bukkit-plugins/ban-management/pages/developer-builds/)

**Comment by confuser** [comment]
Same issue as before. You can simply disable the leak detection. 

However, by the looks of it, it seems like your syncing queries are taking longer than 3 seconds. Sounds like you may have a connectivity issue from your server to the database. I'd recommend running a ping from your minecraft server to the database server to check the latency and see if you receive any time outs to confirm.
