### ISSUE TITLE
"Could not pass event PlayerBannedEvent" when banning player

### ISSUE THREAD

**Issue by Martyn96** [BanManagement/BanManager#577]
Getting the following exception when banning a player. The ban does go through though.

```
[00:19:29] [Craft Scheduler Thread - 1082/ERROR]: Could not pass event PlayerBannedEvent to BanManager v5.9.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.2.jar:git-Paper-640]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-640]
	at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:124) [BanManager.jar:?]
	at me.confuser.banmanager.commands.BanCommand$1.run(BanCommand.java:138) [BanManager.jar:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched_1.9.2.jar:git-Paper-640]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.9.2.jar:git-Paper-640]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalStateException: Asynchronous entity track!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.EntityTracker.addEntity(EntityTracker.java:105) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.EntityTracker.track(EntityTracker.java:87) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.WorldManager.a(WorldManager.java:18) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.World.b(World.java:1114) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:1135) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.WorldServer.a(WorldServer.java:1100) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.Chunk.addEntities(Chunk.java:835) ~[patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14) ~[patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:17) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:167) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:96) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:349) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:345) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.World.getType(World.java:836) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.TileEntityCommand$1.i(TileEntityCommand.java:31) ~[patched_1.9.2.jar:git-Paper-640]
	at net.minecraft.server.v1_9_R1.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:270) ~[patched_1.9.2.jar:git-Paper-640]
	at org.bukkit.craftbukkit.v1_9_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27) ~[patched_1.9.2.jar:git-Paper-640]
	at me.confuser.banmanager.util.CommandUtils.broadcast(CommandUtils.java:66) ~[?:?]
	at me.confuser.banmanager.listeners.BanListener.notifyOnBan(BanListener.java:44) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor79.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.2.jar:git-Paper-640]
	... 12 more
```

**Comment by confuser** [comment]
Are you running Paper Spigot? I'm not familiar with what differences it has vs Spigot. By the looks of it, it's complaining about sending a message to players async.

**Comment by Martyn96** [comment]
Yes I'm using Paper. Just gave the server a restart though and the issue no longer occurs.

**Comment by confuser** [comment]
It might be worth raising this with Paper. As far as I'm aware, `sendMessage` is supposed to be thread safe.

**Comment by Brokkonaut** [comment]
sendMessage to players is (mostly) thread safe, but you use sendMessage to a command block (BlockCommandSender). that is not thread safe at all.

**Comment by confuser** [comment]
@Brokkonaut Thanks, however, I'm not explicitly sending messages to command blocks.

`getPermissionSubscriptions("bukkit.broadcast.user")` then looping through users. I've added checks to ensure it doesn't accidentally send messages to command block instances, however, I'd like to understand the issue better. I can see the problem is that sendMessage causes a chunk to load async. I've only had reports from users using Paper throwing this exception. So is it simply that Paper is implementing additional async checks to warn about bad plugins, compared to Spigot?

**Comment by Brokkonaut** [comment]
Yes, Paper has a lot of additional checks to prevent accidental async access.
