### ISSUE TITLE
Need help minecraft 1.7.10 java 7

### ISSUE THREAD

**Issue by DevinderFTW** [BanManagement/BanManager#579]
```
[18:15:10 WARN]: java.lang.IllegalStateException: Errors getting more results of class me.confuser.banmanager.data.IpMuteData
[18:15:10 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:103)
[18:15:10 WARN]:        at me.confuser.banmanager.runnables.ExpiresSync.run(ExpiresSync.java:105)
[18:15:10 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
[18:15:10 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[18:15:10 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:15:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:15:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:15:10 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:15:10 WARN]: Caused by: java.sql.SQLException: Connection is closed
[18:15:10 WARN]:        at me.confuser.banmanager.internal.hikari.pool.ProxyConnection$ClosedConnection$1.invoke(ProxyConnection.java:465)
[18:15:10 WARN]:        at com.sun.proxy.$Proxy38.clearWarnings(Unknown Source)
[18:15:10 WARN]:        at me.confuser.banmanager.internal.hikari.pool.ProxyConnection.close(ProxyConnection.java:238)
[18:15:10 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.close(JdbcDatabaseConnection.java:139)
[18:15:10 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.releaseConnection(DataSourceConnectionSource.java:130)
[18:15:10 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.close(SelectIterator.java:247)
[18:15:10 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:84)
[18:15:10 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
[18:15:10 WARN]:        ... 7 more
[18:15:12 WARN]: 17565838 [HikariPool-0 housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@431b3818, stack trace follows

[18:15:12 WARN]: java.lang.Exception: Apparent connection leak detected
[18:15:12 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
[18:15:12 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
[18:15:12 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
[18:15:12 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
[18:15:12 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
[18:15:12 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
[18:15:12 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
[18:15:12 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.Where.iterator(Where.java:538)
[18:15:12 WARN]:        at me.confuser.banmanager.runnables.ExpiresSync.run(ExpiresSync.java:103)
[18:15:12 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
[18:15:12 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[18:15:12 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:15:12 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:15:12 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:15:12 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by DevinderFTW** [comment]
Also this while starting server:

[19:51:51 INFO]: [BanManager] Enabling BanManager v5.9.0
[19:52:10 WARN]: 5346 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-0 - Started.

[19:52:20 WARN]: 15786 [Server thread] WARN me.confuser.banmanager.internal.hikari.pool.PoolBase - HikariPool-0 - Failed to get/set network timeout for connection. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)

[19:52:26 WARN]: 21373 [HikariPool-0 housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@594f8d2d, stack trace follows

[19:52:26 WARN]: java.lang.Exception: Apparent connection leak detected
[19:52:26 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
[19:52:26 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
[19:52:26 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.queryForId(BaseDaoImpl.java:221)
[19:52:26 WARN]:        at me.confuser.banmanager.storage.PlayerStorage.setupConsole(PlayerStorage.java:61)
[19:52:26 WARN]:        at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:44)
[19:52:26 WARN]:        at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:309)
[19:52:26 WARN]:        at me.confuser.banmanager.BanManager.onEnable(BanManager.java:116)
[19:52:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[19:52:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[19:52:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[19:52:26 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[19:52:26 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[19:52:26 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500)
[19:52:26 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474)
[19:52:26 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434)
[19:52:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[19:52:26 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
[19:52:26 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by confuser** [comment]
You have some serious problems with your database. Queries are taking a long time, some are timing out, connections are being closed.
