### ISSUE TITLE
Error when Banmanger tries to collect timings from paperspigot

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#600]
Im under the assumption this error is related with BanManager as it shows up in the error.
The latest PaperSpigot uses the better, updated timings v2 system, banmanger looks like its struggling to work with it.
`[20:46:34] [Craft Scheduler Thread - 3031/ERROR]: stopTiming called async for PirateCraft_1_nether - chunkLoad - Entities
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: java.lang.Throwable
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:111)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:379)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:17)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:173)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:154)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:150)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:97)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.World.getChunkAt(World.java:350)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.World.getChunkAtWorldCoords(World.java:346)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.World.getType(World.java:837)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.TileEntityCommand$1.i(TileEntityCommand.java:31)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at net.minecraft.server.v1_9_R1.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:270)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at me.confuser.banmanager.util.CommandUtils.broadcast(CommandUtils.java:66)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at me.confuser.banmanager.listeners.JoinListener$1.run(JoinListener.java:219)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[20:46:34] [Craft Scheduler Thread - 3031/WARN]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by confuser** [comment]
This is most likely due to #597. Please update to a dev build and let me know if it's still an issue or not.

**Comment by FrozenBeard** [comment]
Awesome, all right, I've updated and Ill keep and eye on my logs.

**Comment by confuser** [comment]
Hi @FrozenBeard, any updates?

**Comment by FrozenBeard** [comment]
I think were good, I can't see any recent error messages, but I will keep monitoring!

**Comment by confuser** [comment]
Great, thanks for confirming. I'll re-open if it's still an issue.
