### ISSUE TITLE
PlayerQuitEvent stacktrace

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#612]
Happened after a player joined the server at restart (directly after update to latest snapshot build no 75) and immedieatly lost connection. It is not perfectly reproducable, out of 4 times it happened twice. Does not seem major.

```
2016-05-24 02:49:16 [INFO] PlayerXY lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: object is not an instance of declaring class
2016-05-24 02:31:41 [ERROR] Could not pass event PlayerQuitEvent to BanManager v5.10.0-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PlayerList.disconnect(PlayerList.java:385) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1059) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.NetworkManager.handleDisconnection(NetworkManager.java:316) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:174) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-8a048fe-a022dd2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.lang.NullPointerException
        at me.confuser.banmanager.listeners.LeaveListener.onLeave(LeaveListener.java:21) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_95]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_95]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8a048fe-a022dd2]
        ... 12 more

**Comment by confuser** [comment]
Can you clarify `Immediately lost connection`? Did they start to join the server but then left?

**Comment by Kakifrucht** [comment]
I think they got disconnected out of some reason not related to BanManager. This might be an issue with ProtocolLib, but BanManager seems to have issues with that happening.

The first two lines are what happened before the actual stacktrace https://pastebin.com/zJ8G8N8a

So complete log would be Player connect, player immediate disconnect, BanManager throws this error once and Protocollib spams it's stack trace a couple of time.
