### ISSUE TITLE
NullPointerException on ResultSetImpl while executing task

### ISSUE THREAD

**Issue by Foorack** [BanManagement/BanManager#617]
Running (latest) version 5.9.0.

`[00:33:33] [Craft Scheduler Thread - 269/WARN]: Exception in thread "Craft Scheduler Thread - 269"
[00:33:33] [Craft Scheduler Thread - 269/WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.9.0 generated an exception while executing task 6711
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6341)
        at me.confuser.banmanager.internal.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseResults.next(JdbcDatabaseResults.java:64)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:81)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
        at me.confuser.banmanager.listeners.JoinListener$1.run(JoinListener.java:204)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
`

**Comment by confuser** [comment]
Interesting, this one is new. It appears the iterator for checking player notes was null.
