### ISSUE TITLE
Could not build prepared-quary Iterator for PlayerMuteData

### ISSUE THREAD

**Issue by Foorack** [BanManagement/BanManager#618]
SQLException instead of NPE this time. Running (latest) version 5.9.0.

`
[17:54:56 WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.PlayerMuteData
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
[17:54:56 WARN]:        at me.confuser.banmanager.storage.PlayerMuteStorage.findMutes(PlayerMuteStorage.java:172)
[17:54:56 WARN]:        at me.confuser.banmanager.runnables.MuteSync.newMutes(MuteSync.java:30)
[17:54:56 WARN]:        at me.confuser.banmanager.runnables.MuteSync.run(MuteSync.java:22)
[17:54:56 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
[17:54:56 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
[17:54:56 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[17:54:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:54:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:54:56 WARN]:        at java.lang.Thread.run(Thread.java:745)
[17:54:56 WARN]: Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30000ms.
[17:54:56 WARN]:        at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
[17:54:56 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
[17:54:56 WARN]:        ... 12 more
`

**Comment by confuser** [comment]
> java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30000ms

Your MySQL database is having connection issues

**Comment by Foorack** [comment]
@confuser Interesting as the database is localhost. Thanks.
