### ISSUE TITLE
Async Tick?

### ISSUE THREAD

**Issue by ryans1230** [BanManagement/BanManager#640]
`2016-07-06 17:30:40 [WARN] org.apache.commons.lang.UnhandledException: Plugin BanManager v5.6.0 generated an exception while executing task 1913764
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous entity track!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:104)
	at net.minecraft.server.v1_10_R1.EntityTracker.track(EntityTracker.java:86)
	at net.minecraft.server.v1_10_R1.WorldManager.a(WorldManager.java:19)
	at net.minecraft.server.v1_10_R1.World.b(World.java:1028)
	at net.minecraft.server.v1_10_R1.WorldServer.b(WorldServer.java:1126)
	at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1091)
	at net.minecraft.server.v1_10_R1.Chunk.addEntities(Chunk.java:753)
	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:136)
	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:119)
	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
	at net.minecraft.server.v1_10_R1.World.getChunkAt(World.java:329)
	at net.minecraft.server.v1_10_R1.World.getChunkAtWorldCoords(World.java:325)
	at net.minecraft.server.v1_10_R1.World.getType(World.java:753)
	at net.minecraft.server.v1_10_R1.TileEntityCommand$1.i(TileEntityCommand.java:33)
	at net.minecraft.server.v1_10_R1.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:271)
	at org.bukkit.craftbukkit.v1_10_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27)
	at me.confuser.banmanager.util.CommandUtils.broadcast(CommandUtils.java:59)
	at me.confuser.banmanager.listeners.JoinListener$2.run(JoinListener.java:300)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

**Comment by ryans1230** [comment]
The above error was with what appears to be no commands being run.

The below error was when the ban command was issued on a player from console:
`2016-07-06 17:34:30 [ERROR] Could not pass event PlayerBannedEvent to BanManager v5.6.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:114) [BanManager.jar:?]
	at me.confuser.banmanager.commands.BanCommand$1.run(BanCommand.java:153) [BanManager.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalStateException: Asynchronous entity track!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:104) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.EntityTracker.track(EntityTracker.java:86) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.WorldManager.a(WorldManager.java:19) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.World.b(World.java:1028) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.WorldServer.b(WorldServer.java:1126) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1091) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.Chunk.addEntities(Chunk.java:753) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:136) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:119) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.World.getChunkAt(World.java:329) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.World.getChunkAtWorldCoords(World.java:325) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.World.getType(World.java:753) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.TileEntityCommand$1.i(TileEntityCommand.java:33) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:271) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at me.confuser.banmanager.util.CommandUtils.broadcast(CommandUtils.java:59) ~[?:?]
	at me.confuser.banmanager.listeners.BanListener.notifyOnBan(BanListener.java:42) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	... 10 more`

**Comment by Kakifrucht** [comment]
That's not the latest build.

**Comment by ryans1230** [comment]
This the first time the error has been seen. And we can't use the latest build due to SQL problems introduced in the latest build.

**Comment by Kakifrucht** [comment]
So what do you expect? If he fixes this you would have to update to the latest build either way.

**Comment by confuser** [comment]
This was already fixed in the latest public release

**Comment by confuser** [comment]
FYI as you didn't respond to my request for the debug output in your other issue, there's very little I can do to support you. Please see all changes between v5.6.0 and v5.7.0, https://github.com/BanManagement/BanManager/compare/v5.6.0...v5.7.0

There were little to no changes at the database layer. The main change was to do with the way syncing is handled, forcing it all into the same thread rather than across multiple threads.
