### ISSUE TITLE
Error related to Local Database

### ISSUE THREAD

**Issue by MrMurfy** [BanManagement/BanManager#643]
Hi, im trying to use BanManager in my server but there is a problem.
-If i try to disable local database, it says:

`[17:46:42] [Server thread/INFO]: [BanManager] Enabling BanManager v5.10.1
[17:46:42] [Server thread/WARN]: [BanManager] Local Database is not enabled, disabling plugin
[17:46:42] [Server thread/INFO]: [BanManager] Disabling BanManager v5.10.1`

-If i try to enable it, then it says:

`[18:08:54] [Server thread/INFO]: [BanManager] Enabling BanManager v5.10.1
[18:08:54] [Server thread/WARN]: 74 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-1 - Started.
[18:09:22] [Server thread/WARN]: 28320 [Server thread] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool - HikariPool-1 - Close initiated...
[18:09:22] [Server thread/WARN]: 28321 [Server thread] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool - HikariPool-1 - Closed.
[18:09:22] [Server thread/ERROR]: Error occurred while enabling BanManager v5.10.1 (Is it up to date?)
me.confuser.banmanager.internal.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:528) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.<init>(HikariPool.java:118) ~[?:?]
	at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.isTableExists(BaseDaoImpl.java:689) ~[?:?]
	at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:40) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:326) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141) [PerWorldPlugins-1.9.4.1.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2164) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2089) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518) ~[?:?]
	... 20 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2089) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518) ~[?:?]
	... 20 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_91]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2089) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518) ~[?:?]
	... 20 more`

And when i stop it in this option, it says:
`[18:09:43] [Server thread/ERROR]: Error occurred while disabling BanManager v5.10.1 (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.BanManager.onDisable(BanManager.java:164) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:136) [PerWorldPlugins-1.9.4.1.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:341) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:459) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:607) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]`

**Comment by MrMurfy** [comment]
What can i do if i dont want to use Local Database atm?

**Comment by confuser** [comment]
Local is required. In this case, local refers to localised bans, but not necessarily a local database. You can use a remote database.
