### ISSUE TITLE
Can't launch server with 101 BM build on old database.

### ISSUE THREAD

**Issue by Ghostlyr** [BanManagement/BanManager#654]
I'm trying to update BM to newest build, but am getting NPE on server start.
This problem observed only on connect to older database (works fine on 99 build).
There have been some changes in the player UUID's data structure?

```
Error occurred while enabling BanManager v5.11.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.util.UUIDUtils.fromBytes(UUIDUtils.java:82) ~[?:?]
	at me.confuser.banmanager.storage.PlayerBanStorage.loadAll(PlayerBanStorage.java:96) ~[?:?]
	at me.confuser.banmanager.storage.PlayerBanStorage.<init>(PlayerBanStorage.java:46) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:329) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.55]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1614.55]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1614.55]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:513) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:487) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:447) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

**Comment by confuser** [comment]
There haven't been any changes in the data structure yet. However, startup queries were optimised. Looks like you have an actor for a particular ban that doesn't exist. Are you deleting any records from bm_players?

**Comment by Ghostlyr** [comment]
No one records are not deleted. I have installed script on site to list bans, All data are collected without mistakes.

**Comment by Ghostlyr** [comment]
Really .. One still showed up with a non-existent uuid. Thank you!
