### ISSUE TITLE
/report does not work for me

### ISSUE THREAD

**Issue by Janunez** [BanManagement/BanManager#663]
When i do /report test123 test it gives me this error
How can i fix this?
[21:06:58 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerReportData@1f7f710d: INSERT INTO `bm_player_reports` (`player_id` ,`reason` ,`actor_id` ,`state_id` ,`assignee_id` ,`created` ,`updated` ) VALUES (?,?,?,?,?,?,?)
[21:06:58 WARN]:        at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[21:06:58 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[21:06:58 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[21:06:58 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[21:06:58 WARN]:        at me.confuser.banmanager.storage.PlayerReportStorage.report(PlayerReportStorage.java:55)
[21:06:58 WARN]:        at me.confuser.banmanager.commands.ReportCommand$1.run(ReportCommand.java:126)
[21:06:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[21:06:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:06:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:06:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:06:58 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:06:58 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'assignee_id' cannot be null
[21:06:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:06:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:06:58 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:06:58 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:06:58 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[21:06:58 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[21:06:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[21:06:58 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[21:06:58 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[21:06:58 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[21:06:58 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[21:06:58 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[21:06:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[21:06:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[21:06:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[21:06:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[21:06:58 WARN]:        at me.confuser.banmanager.internal.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[21:06:58 WARN]:        at me.confuser.banmanager.internal.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[21:06:58 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[21:06:58 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[21:06:58 WARN]:        ... 9 more

**Comment by EvilOlaf** [comment]
Did you upgrade from an older version that did not have the reports feature or was still in early development? AFAIR there was an update for BM with the hint to remove any existing tables relating to the warning thing as you could run into trouble if not.
So what you can give a try is removing those tables (as always backup first) and start the server to let BM recreate them.

Would also be useful what version you are running on.

**Comment by confuser** [comment]
Please update to the latest developer build. It's already fixed.

http://ci.frostcast.net/job/BanManager/

**Comment by Janunez** [comment]
okay thanks it works now
