### ISSUE TITLE
Database Not Connecting v 5.11

### ISSUE THREAD

**Issue by pricey123** [BanManagement/BanManager#665]
The new error after updating is as follows

`[15:04:41] [Server thread/INFO]: [BanManager] Enabling BanManager v5.11.0
[15:04:41] [Server thread/INFO]: [BanManager] Converting external connection details to global
[15:04:41] [Server thread/INFO]: [BanManager] Converted external connection details to global
[15:04:41] [Server thread/WARN]: 56 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - bm-local - Started.

[15:04:41] [Server thread/ERROR]: Error occurred while enabling BanManager v5.11.0 (Is it up to date?)
java.lang.IllegalAccessError: class me.confuser.banmanager.internal.hikari.pool.HikariPool cannot access its superclass me.confuser.banmanager.internal.hikari.pool.PoolBase
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_101]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_101]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_101]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_101]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.isTableExists(BaseDaoImpl.java:689) ~[?:?]
	at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:40) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:328) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[15:04:41] [Server thread/INFO]: [BanManager] Disabling BanManager v5.11.0
[15:04:41] [Server thread/ERROR]: Error occurred while disabling BanManager v5.11.0 (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.BanManager.onDisable(BanManager.java:164) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]`

**Comment by confuser** [comment]
Did you use a plugin manager to load this? Please try a full server restart.
