### ISSUE TITLE
Warns in Console.

### ISSUE THREAD

**Issue by BlackLottus** [BanManagement/BanManager#694]
Hi.

¿This is normal?

[14:13:30 INFO]: Christianizqui45 has been permanently muted by Antonio46 for Pasar contenido pornogrßfico.
[14:13:43 INFO]: 201.251.91.36 (Facuton) has been permanently banned by Black_Lottus for Uso indebido de Hacks - By iRyukTenma (Fue Úl)
[14:13:46 WARN]: 89104 [bm-local housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@801d29, stack trace follows

[14:13:46 WARN]: java.lang.Exception: Apparent connection leak detected
[14:13:46 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
[14:13:46 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
[14:13:46 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
[14:13:46 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:196)
[14:13:46 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:265)
[14:13:46 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:361)
[14:13:46 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.Where.query(Where.java:503)
[14:13:46 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.queryForEq(BaseDaoImpl.java:245)
[14:13:46 WARN]:        at me.confuser.banmanager.storage.IpBanStorage.retrieveBan(IpBanStorage.java:119)
[14:13:46 WARN]:        at me.confuser.banmanager.runnables.GlobalIpSync.newBans(GlobalIpSync.java:44)
[14:13:46 WARN]:        at me.confuser.banmanager.runnables.GlobalIpSync.run(GlobalIpSync.java:28)
[14:13:46 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.java:27)
[14:13:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:13:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:13:46 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:13:46 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:13:46 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:13:56 WARN]: 98897 [bm-local housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@801d29, stack trace follows

[14:13:56 WARN]: java.lang.Exception: Apparent connection leak detected
[14:13:56 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
[14:13:56 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
[14:13:56 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
[14:13:56 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:196)
[14:13:56 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:265)
[14:13:56 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:361)
[14:13:56 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.Where.query(Where.java:503)
[14:13:56 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.queryForEq(BaseDaoImpl.java:245)
[14:13:56 WARN]:        at me.confuser.banmanager.storage.IpBanStorage.retrieveBan(IpBanStorage.java:119)
[14:13:56 WARN]:        at me.confuser.banmanager.runnables.GlobalIpSync.newBans(GlobalIpSync.java:44)
[14:13:56 WARN]:        at me.confuser.banmanager.runnables.GlobalIpSync.run(GlobalIpSync.java:28)
[14:13:56 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.java:27)
[14:13:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:13:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:13:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:13:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:13:56 WARN]:        at java.lang.Thread.run(Unknown Source)

And why appers? Can help me? Ty

**Comment by confuser** [comment]
That's normal if your database connection is slow, causing queries to take longer than expected to be completed.

If this occurs quite often, you can either increase `leakDetection` or disable it completely by setting it to 0. This can be found in your config.yml file, under databases.

**Comment by BlackLottus** [comment]
But, if I set the detection to 0, does it mean that you will be buying all the time if a ban is made?

Will not this produce lag?

**Comment by BlackLottus** [comment]
Sorry.
that it will be checking the entire time for a ban?
Not buy

**Comment by confuser** [comment]
It won't cause any lag to your minecraft server, everything is performed asynchronously. It may delay ban syncing.

**Comment by BlackLottus** [comment]
Ok, Thanks

I Try and if you fail again something I will certainly let you know.
Thank you very much: 3
