### ISSUE TITLE
Conversions from v4 - lack of documentation

### ISSUE THREAD

**Issue by feardevilz** [BanManagement/BanManager#696]
Hi, 
after reviewing the documents there's a lack of upgrade instructions and quite frankly, horrible documentation leads to disasters. Related to https://github.com/BanManagement/BanManager/issues/544 which was not really answered, where are the conversion database instructions? Per https://dev.bukkit.org/projects/ban-management/pages/uuid-update step 16 indicated "Add in the conversion database connection details. ". Per the prior issue, the conversion was removed in 5.9. Is there any way to perform upgrades from 3.x or 4.x to 5.13, if so how?

It appears that simply adding the old config "localDatabase" and "externalDatabase" into the new confg on 5.13 does not initiate the move. Someone needs to rewrite the old documentation to provide a better upgrade path.

**Comment by confuser** [comment]
Use a pre 5.9 version, then update to 5.13

**Comment by feardevilz** [comment]
Attempted to use 5.8 but using an older rev just means you have to downgrade the entire server again. 
`[16:15:28] [Server thread/INFO]: [BanManager] Conversion will begin shortly. You have 30 seconds to kill the process to abort.
[16:15:58] [Server thread/INFO]: [BanManager] Launching conversion process
[16:15:58] [Server thread/WARN]: 31692 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-1 - is starting.

[16:15:58] [Server thread/INFO]: [BanManager] Requesting UUID for 66viper66 at 1406323691
[16:16:00] [Server thread/ERROR]: Error occurred while enabling BanManager v5.8.0 (Is it up to date?)
java.lang.NullPointerException
        at me.confuser.banmanager.storage.PlayerStorage.createOrUpdate(PlayerStorage.java:97) ~[?:?]
        at me.confuser.banmanager.storage.conversion.converters.Converter.findAndCreate(Converter.java:41) ~[?:?]
        at me.confuser.banmanager.storage.conversion.converters.PlayerIpConverter.run(PlayerIpConverter.java:34) ~[?:?]
        at me.confuser.banmanager.storage.conversion.UUIDConvert.executeConverter(UUIDConvert.java:98) ~[?:?]
        at me.confuser.banmanager.storage.conversion.UUIDConvert.<init>(UUIDConvert.java:22) ~[?:?]
        at me.confuser.banmanager.BanManager.setupConversion(BanManager.java:196) ~[?:?]
        at me.confuser.banmanager.BanManager.onEnable(BanManager.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[server.jar:git-Spigot-850da7e-e20928f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-850da7e-e20928f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-850da7e-e20928f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [server.jar:git-Spigot-850da7e-e20928f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [server.jar:git-Spigot-850da7e-e20928f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [server.jar:git-Spigot-850da7e-e20928f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [server.jar:git-Spigot-850da7e-e20928f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [server.jar:git-Spigot-850da7e-e20928f]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [server.jar:git-Spigot-850da7e-e20928f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [server.jar:git-Spigot-850da7e-e20928f]
        at java.lang.Thread.run(Thread.java:744) [?:1.8.0-ea]`

**Comment by confuser** [comment]
Try setting `offlineAutoComplete` to false in your config. Why are you trying to convert a v4 database, if you're already running v5?

**Comment by feardevilz** [comment]
setting offlineAutoComplete to false did the trick. Your instructions have users installing v5 first before trying a migration. The users we migrated haven't used banmanger in 3 years. Is there any chance you can upgrade the instructions so other users don't have the same issues?

**Comment by confuser** [comment]
I've already updated the documentation. Hopefully it is much clearer now.
