### ISSUE TITLE
WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#713]
Version 5.13.1
Spigot:  git-paper916 MC 1.10.2

I miss-typed tempmute forgetting the temp, and I noticed a serious error:

```
[12:58:59] [Server thread/INFO]: GodsDead issued server command: /mute MasterM1214 20m
[12:59:02] [bm-local housekeeper/WARN]: 129180 [bm-local housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@106facaf, stack trace follows

[12:59:02] [bm-local housekeeper/WARN]: java.lang.Exception: Apparent connection leak detected
[12:59:02] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
[12:59:02] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308)
[12:59:02] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.storage.PlayerMuteStorage.mute(PlayerMuteStorage.java:191)
[12:59:02] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.commands.MuteCommand$1.run(MuteCommand.java:154)
[12:59:02] [bm-local housekeeper/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[12:59:02] [bm-local housekeeper/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:59:02] [bm-local housekeeper/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:59:02] [bm-local housekeeper/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:59:02] [bm-local housekeeper/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:59:02] [bm-local housekeeper/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:59:02] [Craft Scheduler Thread - 1009/INFO]: MasterM1214 has been permanently muted by GodsDead for 20m
[12:59:12] [Server thread/INFO]: GodsDead issued server command: /unmute MasterM1214
[12:59:15] [bm-local housekeeper/WARN]: 141877 [bm-local housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@106facaf, stack trace follows

[12:59:15] [bm-local housekeeper/WARN]: java.lang.Exception: Apparent connection leak detected
[12:59:15] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
[12:59:15] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308)
[12:59:15] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.storage.PlayerMuteRecordStorage.addRecord(PlayerMuteRecordStorage.java:41)
[12:59:15] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.storage.PlayerMuteStorage.unmute(PlayerMuteStorage.java:222)
[12:59:15] [bm-local housekeeper/WARN]: 	at me.confuser.banmanager.commands.UnmuteCommand$1.run(UnmuteCommand.java:92)
[12:59:15] [bm-local housekeeper/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[12:59:15] [bm-local housekeeper/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:59:15] [bm-local housekeeper/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:59:15] [bm-local housekeeper/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:59:15] [bm-local housekeeper/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:59:15] [bm-local housekeeper/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by confuser** [comment]
It's a warning that your queries to the DB are taking a long time to run. If this is expected, feel free to ignore. If not, I'd recommend investigating your MySQL database.
