### ISSUE TITLE
Unable to get driver instance.

### ISSUE THREAD

**Issue by MachineGalaxy** [BanManagement/BanManager#726]
# Issue report

**Tell us about your environment**

* **Server Software:** 
CraftBukkit version git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
* **Server Version:**
Minecraft 1.7.10
* **BanManager Version:**
BanManager version 5.8.0

* **Online/Offline mode**: Online

**BanManager config.yml**:

```yaml

# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    host: http://fxnetwork.net/
    port: 3306
    name: 
    user: 
    password: 
    maxConnections: 10
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
  external:
    enabled: true
    host: http://fxnetwork.net/
    port: 3306
    name: 
    user: 
    password: 
    maxConnections: 10
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
  convert:
    enabled: false
    host: 
    port: 3306
    name: 
    user: 
    password: 
    maxConnections: 10
    tables:
      bansTable: bm_bans
      bansRecordTable: bm_ban_records
      ipBansTable: bm_ip_bans
      ipBansRecordTable: bm_ip_records
      kicksTable: bm_kicks
      mutesTable: bm_mutes
      mutesRecordTable: bm_mutes_records
      playerIpsTable: bm_player_ips
      warningsTable: bm_warnings
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: false
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
checkOnJoin: false


```

**Describe your issue:** 
 **Problem**: The plugin is not making the tables in the data base. I believe it is because it is unable to get driver instance for the data base but I don't know how to fix this problem. The Collation for the data base is utf8_unicode_ci.

**Console Output**:
 ```[12:22:20] [Server thread/INFO]: [BanManager] Enabling BanManager v5.8.0
[12:22:21] [Server thread/WARN]: 137 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-0 - is starting.

[12:22:21] [Server thread/ERROR]: Error occurred while enabling BanManager v5.8.0 (Is it up to date?)
java.lang.RuntimeException: Unable to get driver instance for jdbcUrl=jdbc:mysql://http://fxnetwork.net/:3306/BansNewEvo_DB?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useUnicode=true&characterEncoding=utf-8
	at me.confuser.banmanager.internal.hikari.util.DriverDataSource.<init>(DriverDataSource.java:88) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:296) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.PoolBase.<init>(PoolBase.java:84) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.<init>(HikariPool.java:102) ~[?:?]
	at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.isTableExists(BaseDaoImpl.java:689) ~[?:?]
	at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:40) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:395) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:118) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:352) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:326) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:282) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(Unknown Source) ~[?:1.8.0_101]
	at me.confuser.banmanager.internal.hikari.util.DriverDataSource.<init>(DriverDataSource.java:81) ~[?:?]
	... 21 more 


```

 
**Further information:**
If anyone can help that would be very useful.

**Comment by Fuechschen** [comment]
You have `http://fxnetwork.net/` as you host, however that is already an url. Change your host to `fxnetwork.net` and it should work

**Comment by MachineGalaxy** [comment]
Thanks

Ill try that now.

**Comment by MachineGalaxy** [comment]
I'm now getting a different error.

``` 
[12:56:46] [Server thread/INFO]: [BanManager] Enabling BanManager v5.8.0
[12:56:46] [Server thread/WARN]: 79 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-0 - is starting.

[12:57:16] [Server thread/WARN]: 30120 [Server thread] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool - HikariPool-0 - is closing down.

[12:57:21] [Server thread/ERROR]: Error occurred while enabling BanManager v5.8.0 (Is it up to date?)
me.confuser.banmanager.internal.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30001ms.
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.<init>(HikariPool.java:136) ~[?:?]
	at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102) ~[?:?]
	at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.isTableExists(BaseDaoImpl.java:689) ~[?:?]
	at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:40) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:395) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:118) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:352) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:326) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:282) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Server.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30001ms.
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:195) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:147) ~[?:?]
	at me.confuser.banmanager.internal.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510) ~[?:?]
	... 19 more


```

**Comment by confuser** [comment]
Failing to connect to the database. Does your MySQL database on `fxnetwork.net` accept external MySQL connections?

**Comment by MachineGalaxy** [comment]
Yes the database can accept external connections, I did however have to change the address from fxnetwork.net to the main ip.
