### ISSUE TITLE
Not Working Properly

### ISSUE THREAD

**Issue by Craftymatt2** [BanManagement/BanManager#739]
#736  Issue report

**Tell us about your environment**
So we host a bungee minecraft network and have decided to use ban manager as it works with our website (nameless), however we have been having **lots** of problems.

* **Server Software:** Spigot 1.10.2 (hosted by server.pro)
* **Server Version:** 1.10.2
* **BanManager Version:**  5.14.0 

* **Online/Offline mode**: Proxy is online, other 3 servers offline
* **Bungeecoord online/offline mode (if applicable)**: Proxy is online, other 3 servers offline

**BanManager config.yml**:

Well we have bungee so its in multiple servers but its the same in each one
```
# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    host: ***************
    port: ***************
    name: ***************
    user: ***************
    password: ***************
    maxConnections: 10
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: true
    host: ***************
    port: ***************
    name: ***************
    user: ***************
    password: ***************
    maxConnections: 10
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- ***************
logKicks: false
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
checkOnJoin: false
createNoteReasons: false
onlineMode: true
chatPriority: normal
```

**Describe your issue:** 

So things are going wrong, when i try to ban someone it sometimes just returns "/ban <player> <reason>". And sometimes it says player not found, even though they are online.

This is when it says the player is not found

```
[20:08:35 WARN]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/profiles/minecraft
[20:08:35 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
[20:08:35 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[20:08:35 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[20:08:35 WARN]:        at me.confuser.banmanager.util.UUIDUtils.call(UUIDUtils.java:183)
[20:08:35 WARN]:        at me.confuser.banmanager.util.UUIDUtils.getUUIDOf(UUIDUtils.java:93)
[20:08:35 WARN]:        at me.confuser.banmanager.storage.PlayerStorage.retrieve(PlayerStorage.java:164)
[20:08:35 WARN]:        at me.confuser.banmanager.util.CommandUtils.getPlayer(CommandUtils.java:141)
[20:08:35 WARN]:        at me.confuser.banmanager.util.CommandUtils.getPlayer(CommandUtils.java:158)
[20:08:35 WARN]:        at me.confuser.banmanager.commands.BanCommand$1.run(BanCommand.java:96)
[20:08:35 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:08:35 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:08:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[20:08:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[20:08:35 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

And when it returns "/ban <player> <reason>" nothing happens in console

**How to replicate:** 

Just attempt to ban someone
 
**Further information:**

When we manage to ban people they can also get back online, only occasionally.
 
I don't know how to fix it or why its so broken, please help me.

**Comment by EvilOlaf** [comment]
I do not think this is BMs fault.
429 http error code means that the there are too many requests on the target machine so it cannot or will not handle any more requests like yours.
Either Mojang was overloaded or there are more Minecraft servers hosted on your ip address which generate lots of requests and the rate limit prevents more requests.

**Comment by Craftymatt2** [comment]
Ok, Do you know any way I can fix it?

**Comment by confuser** [comment]
It looks like you're attempting to ban players whom joined the server before BM was installed? The plugin will only make requests to Mojang under the following circumstances:

- Duplicate names found, plugin will request new names (players changed name)
- Player not found in players table
