### ISSUE TITLE
Bug while enabling

### ISSUE THREAD

**Issue by SuperWYLP** [BanManagement/BanManager#742]
* **Server Version: Server Software: git-Spigot-7228328-11323bf (mc: 1.12)
* **BanManager Version: 5.14.0

* **Online/Offline mode**: 
* **Bungeecoord online/offline mode (if applicable)**:  online

**BanManager config.yml**:
debug: false
databases:
  local:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: ****
    user: ****
    password: *************
    maxConnections: 10
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: false
    host: 127.0.0.1
    port: 3306
    name: global_bans
    user: root
    password: ''
    maxConnections: 10
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: true
logIps: true
displayNotifications: true
broadcastOnSync: true
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
checkOnJoin: false
createNoteReasons: false
onlineMode: true
chatPriority: normal

```

**Describe your issue:** 
This comes up after Server startup.
[23:35:16] [Server thread/ERROR]: Error occurred while enabling BanManager v5.14.0 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at me.confuser.banmanager.internal.guava.cache.LocalCache.<clinit>(LocalCache.java:77) ~[?:?]
	at me.confuser.banmanager.internal.guava.cache.LocalCache$LocalManualCache.<init>(LocalCache.java:4702) ~[?:?]
	at me.confuser.banmanager.internal.guava.cache.CacheBuilder.build(CacheBuilder.java:811) ~[?:?]
	at me.confuser.banmanager.storage.PlayerWarnStorage.<init>(PlayerWarnStorage.java:34) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:343) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:135) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [craftbukkit.jar:git-Spigot-7228328-11323bf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**How to replicate:** 
Start the Server on 1.12 and you will get this error
 
**Further information:**
Plugin still works but its not clean in log.

**Comment by EvilOlaf** [comment]
Try using latest BM dev build instead of stable.
