### ISSUE TITLE
Serious error for Mysql and Web Interfaces

### ISSUE THREAD

**Issue by AaronHzy** [BanManagement/BanManager#760]
**Server : PaperSpigot-1.11.2-b1104**
**Bungeecoord : Waterfall-160**
**BanManager Version : 5.15.0**
**Web Interfaces Version : 1.5.8**
**Mysql Version : 5.7.17**
**PHP Version : 7.1**
**Online/Offline mode : Offline**
**Bungeecoord online/offline mode : Offline**

**BanManager config.yml :**
```
debug: false
databases:
  local:
    enabled: true
    host: xxx.xxx.xxx.xxx
    port: 3306
    name: XXXXX
    user: XXXXX
    password: xxxxxxxxxxxxxxxxxx
    maxConnections: 10
    useSSL: true
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: true
    host: xxx.xxx.xxx.xxx
    port: 3306
    name: XXXXX
    user: XXXXX
    password: xxxxxxxxxxxxxxxxxx
    maxConnections: 10
    useSSL: true
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
- friends msg
softMutedCommandBlacklist:
- msg
- friends msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: true
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: false
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 0
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: false
createNoteReasons: false
onlineMode: false
chatPriority: normal
```

**# Mysql issue:**
1.After executing the command “/banipall xx xx xx ” Console error，And the command is not executed

```
[12:17:26 WARN]: handleDisconnection() called twice
[12:17:51 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@6badbbad: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)
[12:17:51 WARN]:        at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[12:17:51 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[12:17:51 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[12:17:51 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[12:17:51 WARN]:        at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:185)
[12:17:51 WARN]:        at me.confuser.banmanager.runnables.GlobalBanSync.newBans(GlobalBanSync.java:53)
[12:17:51 WARN]:        at me.confuser.banmanager.runnables.GlobalBanSync.run(GlobalBanSync.java:29)
[12:17:51 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.java:27)
[12:17:51 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[12:17:51 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:17:51 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:17:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:17:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:17:51 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:17:51 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '\x085\xD4\xB4\xF6\xEE:u\xB3\xEBC\x9A\x9F\x8A>\x84' for key 'bm_player_bans_player_idx'
[12:17:51 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:17:51 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[12:17:51 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[12:17:51 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[12:17:51 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[12:17:51 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[12:17:51 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
[12:17:51 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
[12:17:51 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
[12:17:51 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[12:17:51 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[12:17:51 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
[12:17:51 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[12:17:51 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[12:17:51 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[12:17:51 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
[12:17:51 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[12:17:51 WARN]:        at me.confuser.banmanager.internal.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[12:17:51 WARN]:        at me.confuser.banmanager.internal.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[12:17:51 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[12:17:51 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[12:17:51 WARN]:        ... 12 more```

**# Web Interfaces issue:**
**1.Home search translation**
If I take it “Player” Translate as “玩家ID”，“IP” Translate as “玩家IP”
When I choose "玩家ID" after the choice “玩家IP” Back again "玩家ID" ，My translation is not displayed at this time，The previous translation is shown “Player”(Can not find the translation of this item)

**1.Home "Recent Bans"**
Home page "Recent Bans、Recent Mutes、Recent Warnings" 
Do not show any player，Not working(I can search for banned players)
 
Thank you for seeing this，My English is bad，Sorry!

**Comment by confuser** [comment]
The error doesn't quite match. You're running /banipall, but the error is complaining about a duplicate player ban. The global ban sync task should unban and re-ban the player in question instead of erroring like this. Quite strange. Are you able to reproduce it consistently?

**Comment by AaronHzy** [comment]
The error is here(config.yml)
wrong：offlineAutoComplete:true
√: offlineAutoComplete:false
