### ISSUE TITLE
Commands not working 

### ISSUE THREAD

**Issue by Kikoiscool** [BanManagement/BanManager#775]
Hey, i downloaded Ban Manager but i cant execute any commands fx: if i try to execute /tempban Kikoiscool 30d test. I get this response: "/tempban <player> <timeDiff> <reason>". This works with all commands i have tryed version 5.15.0 and version 6.0.0 SNAPSHOT. The console says: `[21:56:32 WARN]: 81 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - bm-local - Started.

[21:57:00 WARN]: 28640 [Server thread] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool - bm-local - Close initiated...

[21:57:00 WARN]: 28642 [Server thread] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool - bm-local - Closed.

[21:57:00 ERROR]: Error occurred while enabling BanManager v6.0.0-SNAPSHOT (Is it up to date?)
me.confuser.banmanager.internal.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
        at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516) ~[?:?]
        at me.confuser.banmanager.internal.hikari.pool.HikariPool.<init>(HikariPool.java:118) ~[?:?]
        at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[?:?]
        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120) ~[?:?]
        at me.confuser.banmanager.storage.mysql.ConvertMyISAMToInnoDb.<init>(ConvertMyISAMToInnoDb.java:23) ~[?:?]
        at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:341) ~[?:?]
        at me.confuser.banmanager.BanManager.onEnable(BanManager.java:136) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_171]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2094) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2019) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_171]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
        at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
        at me.confuser.banmanager.internal.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
        at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
        ... 17 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_171]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2035) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2019) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_171]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
        at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
        at me.confuser.banmanager.internal.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
        at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
        ... 17 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_171]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_171]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_171]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_171]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_171]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_171]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_171]
        at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_171]
        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2035) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2019) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_171]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
        at me.confuser.banmanager.internal.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
        at me.confuser.banmanager.internal.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
        at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
        ... 17 more` Confuser plz awnser need help
best regards,
Kikoiscool

**Comment by confuser** [comment]
```
Could not create connection to database server. Attempted reconnect 10 times. Giving up.
```
Either your MySQL credentials are incorrect, or it does not accept remote connections from your MC server.
