### ISSUE TITLE
BM not creating tables in mysql database on new load

### ISSUE THREAD

**Issue by lrmtheboss** [BanManagement/BanManager#822]
# Issue report

**Tell us about your environment**

* **Server Software:** paperspigot
* **Server Version:** 237 (1.14.4)
* **BanManager Version:** 6.0.2

* **Online/Offline mode**: offline
* **Bungeecoord online/offline mode (if applicable)**: online

**BanManager config.yml**:

```yaml
# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    storageType: mysql
    enabled: true
    host: 
    port: 3306
    name: 
    user:
    password: 
    maxConnections: 2
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    storageType: mysql
    enabled: true
    host: 
    port: 3306
    name: 
    user: 
    password: 
    maxConnections: 2
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
- w
- r
- mail
- m
- t
- whisper
- emsg
- tell
- er
- reply
- ereply
- email
- action
- describe
- eme
- eaction
- edescribe
- etell
- ewhisper
- pm
softMutedCommandBlacklist:
- msg
- w
- r
- mail
- m
- t
- whisper
- emsg
- tell
- er
- reply
- ereply
- email
- action
- describe
- eme
- eaction
- edescribe
- etell
- ewhisper
- pm
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
- 192.168.1.3
- 192.168.1.1
logKicks: true
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 0
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 3
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: true
createNoteReasons: true
onlineMode: true
chatPriority: normal

```

**Describe your issue:** 

banmanager seem to not be creating the tables in the local MySQL DB even tho the user that it uses has all perms to that database

```Log
[BanManager] Enabling BanManager v6.0.2*
[17:48:06 WARN]: 34 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - bm-local - Starting...
[17:48:06 WARN]: 290 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - bm-local - Start completed.
[17:48:06 WARN]: 310 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - bm-global - Starting...
[17:48:06 WARN]: 317 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - bm-global - Start completed.
[17:48:06 WARN]: [BanManager] An error occurred attempting to make a database connection, please see stack trace below
[17:48:06 INFO]: [BanManager] Disabling BanManager v6.0.2
[17:48:06 WARN]: java.sql.SQLSyntaxErrorException: Table 'bm-hub.bm_players' doesn't exist
[17:48:06 WARN]: at me.confuser.banmanager.internal.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[17:48:06 WARN]: at me.confuser.banmanager.internal.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[17:48:06 WARN]: at me.confuser.banmanager.internal.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[17:48:06 WARN]: at me.confuser.banmanager.internal.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
[17:48:06 WARN]: at me.confuser.banmanager.internal.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020)
[17:48:06 WARN]: at me.confuser.banmanager.internal.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[17:48:06 WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[17:48:06 WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:309)
[17:48:06 WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:229)
[17:48:06 WARN]: at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedQueryForFieldEq.execute(MappedQueryForFieldEq.java:38)
[17:48:06 WARN]: at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.queryForId(StatementExecutor.java:94)
[17:48:06 WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.queryForId(BaseDaoImpl.java:229)
[17:48:06 WARN]: at me.confuser.banmanager.storage.PlayerStorage.setupConsole(PlayerStorage.java:62)
[17:48:06 WARN]: at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:45)
[17:48:06 WARN]: at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:356)
[17:48:06 WARN]: at me.confuser.banmanager.BanManager.onEnable(BanManager.java:138)
[17:48:06 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:48:06 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[17:48:06 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[17:48:06 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[17:48:06 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[17:48:06 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[17:48:06 WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[17:48:06 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[17:48:06 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**How to replicate:** 

 try to start the server or enable the plugin
**Further information:**

i am using it on another server very similar to this one but with more plugins and it works fine on it

**Comment by confuser** [comment]
Not been able to reproduce this. What version of MySQL are you using? Anything else different on this server compared to your others?

**Comment by lrmtheboss** [comment]
MariaDB 10.1.43
just a few less plugins otherwise the same

**Comment by confuser** [comment]
Set `storageType` to `mariadb` in your config

**Comment by lrmtheboss** [comment]
oh thats a option? ok ill try that

**Comment by lrmtheboss** [comment]
yeap that fixed it but why would it work on one and not another?

**Comment by confuser** [comment]
Not sure, perhaps they're different MariaDB versions? If it's working, it should be okay
