### ISSUE TITLE
Plugin fails to load on 1.7 because of NPE

### ISSUE THREAD

**Issue by Sir-Will** [BanManagement/BanManager#888]
I have a weird issue where the plugins fails to load because of the error below. The issue is only on one 1.7.10 server, other 1.7 servers don't have this issue.
Any clue what the issue could be?

I already tried to reset the configs and the plugin but the error seems to come from the plugin.yml inside the jar.
```
[09:44:31] [Server thread/ERROR]: Error occurred while enabling BanManager v7.2.0 (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.bukkit.BMBukkitPlugin.setupConfigs(BMBukkitPlugin.java:99) ~[?:?]
	at me.confuser.banmanager.bukkit.BMBukkitPlugin.onEnable(BMBukkitPlugin.java:45) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.MyM.4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.MyM.4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.MyM.4]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1614.MyM.4]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1614.MyM.4]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

 
BanManagerBukkit-7.2.0.jar and BanManagerBukkit-7.2.2.jar

**Comment by confuser** [comment]
On the affected server, can you open the jar (using any type of archive program) and check the contents on the plugin.yml file? Sounds like `commands` section is missing which is odd

**Comment by Sir-Will** [comment]
Yea, I checked that. I don't see any issue with it: https://pastebin.com/raw/x1rSXYRr
I also copied over the jar from a server where it's working. Very weird.

**Comment by confuser** [comment]
Same Craftbukkit/Spigot version across all servers? Any differences in plugins running between the servers that are working and the one that isn't?

**Comment by Sir-Will** [comment]
Finally, found the issue. When CreeperCollateral mod is installed then BanManager is having this issue. (Older versions didn't have the issue).
