### ISSUE TITLE
Error occurred while executing command: null in a chat

### ISSUE THREAD

**Issue by LeonusDH** [BanManagement/BanManager#912]
```[Server thread/ERROR] [Sponge]: Error occurred while executing command 'ban' for source EntityPlayerMP['LeonusDH'/11, l='spawn', x=1,16, y=92,00, z=-29,81]: null
java.lang.NullPointerException: null
        at me.confuser.banmanager.sponge.SpongePlayer.hasPermission(SpongePlayer.java:104) ~[SpongePlayer.class:?]
        at me.confuser.banmanager.sponge.SpongeCommand.execute(SpongeCommand.java:56) ~[SpongeCommand.class:?]
        at me.confuser.banmanager.sponge.SpongeCommand.process(SpongeCommand.java:44) ~[SpongeCommand.class:?]
        at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.3.1-RC4082]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.3.1-RC4082]
        at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:665) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.3.1-RC4082]
        at net.minecraft.network.PacketThreadUtil$1.redirect$zlc000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:325) [SpongeImplHooks.class:1.12.2-2838-7.3.1-RC4082]
        at net.minecraft.server.MinecraftServer.redirect$zjg000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]```


Sponge: spongeforge-1.12.2-2838-7.3.1-RC4082.jar
BanManager Version: 7.3.1

**BanManager config.yml**:
```# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    storageType: h2
    host: 127.0.0.1
    port: 3306
    name: local_bans
    user: root
    password: ''
    maxConnections: 10
    useSSL: false
    allowPublicKeyRetrieval: false
    verifyServerCertificate: false
    maxLifetime: 1800000
    connectionTimeout: 30000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: false
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: global_bans
    user: root
    password: ''
    maxConnections: 10
    useSSL: false
    allowPublicKeyRetrieval: false
    verifyServerCertificate: false
    leakDetection: 3000
    maxLifetime: 1800000
    connectionTimeout: 30000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: false
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
cooldowns:
  ban: 10
  tempban: 10
  mute: 10
  tempmute: 10
  banip: 10
  tempbanip: 10
  warn: 10
  tempwarn: 10
  report: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
  playerHistory: 0
maxOnlinePerIp: 0
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: false
createNoteReasons: false
onlineMode: false
chatPriority: normal
blockInvalidReasons: false

```

**Comment by LeonusDH** [comment]
Empirically, I found out that if you set onlineMode: false, the commands on behalf of the player stop working and on attempts they will be used writes Error occurred while executing command: null

**Comment by confuser** [comment]
@LeonusDH struggling to reproduce this issue. Can you provide steps to reproduce, i.e. what commands you're running which triggers this problem?

**Comment by LeonusDH** [comment]
@confuser /ban and /mute
