### ISSUE TITLE
Recently installed DiscordSRV.. It messed with my Ban Manager

### ISSUE THREAD

**Issue by uhBonk** [BanManagement/BanManager#919]
As title says, I installed DiscordSRV (spigot and all), configured it and ever since I started doing that, Ban Manager fails to fuction.. Error stack below..

`[19:21:53] [Server thread/INFO]: [DiscordSRV] Enabling DiscordSRV v1.22.0
[19:21:53] [Server thread/INFO]: [BanManager] Enabling BanManager v7.2.2
[19:21:54] [Server thread/WARN]: [Server thread] INFO me.confuser.banmanager.common.hikari.HikariDataSource - bm-local - Starting...
[19:21:54] [Server thread/WARN]: [Server thread] ERROR me.confuser.banmanager.common.hikari.pool.HikariPool - bm-local - Exception during pool initialization.
[19:21:54] [Server thread/WARN]: me.confuser.banmanager.common.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90020 not found) [90020-200]
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.message.DbException.getJdbcSQLException(DbException.java:622)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.message.DbException.getJdbcSQLException(DbException.java:429)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.message.DbException.get(DbException.java:194)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Database.getPageStore(Database.java:2659)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Database.open(Database.java:675)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Database.openDatabase(Database.java:307)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Database.<init>(Database.java:301)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.openSession(Engine.java:74)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.openSession(Engine.java:192)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.createSession(Engine.java:166)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.createSession(Engine.java:29)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.Driver.connect(Driver.java:69)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.ormlite.jdbc.DataSourceConnectionSource.initialize(DataSourceConnectionSource.java:104)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.ormlite.jdbc.DataSourceConnectionSource.<init>(DataSourceConnectionSource.java:71)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.BanManagerPlugin.createConnection(BanManagerPlugin.java:328)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.BanManagerPlugin.setupConnections(BanManagerPlugin.java:274)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.BanManagerPlugin.enable(BanManagerPlugin.java:168)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.bukkit.BMBukkitPlugin.onEnable(BMBukkitPlugin.java:58)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:881)
[19:21:54] [Server thread/WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:651)
[19:21:54] [Server thread/WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[19:21:54] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:748)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[19:21:54] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:21:54] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Minecraft Repository/bonkSMP/plugins/BanManager/local_bans.mv.db [1.4.200/7]
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.FileStore.open(FileStore.java:166)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.MVStore.<init>(MVStore.java:381)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
[19:21:54] [Server thread/WARN]:        ... 44 more
[19:21:54] [Server thread/WARN]: Caused by: java.nio.channels.OverlappingFileLockException
[19:21:54] [Server thread/WARN]:        at sun.nio.ch.SharedFileLockTable.checkList(Unknown Source)
[19:21:54] [Server thread/WARN]:        at sun.nio.ch.SharedFileLockTable.add(Unknown Source)
[19:21:54] [Server thread/WARN]:        at sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
[19:21:54] [Server thread/WARN]:        at java.nio.channels.FileChannel.tryLock(Unknown Source)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.FileStore.open(FileStore.java:163)
[19:21:54] [Server thread/WARN]:        ... 47 more
[19:21:54] [Server thread/WARN]: me.confuser.banmanager.common.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90020 not found) [90020-200]
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.message.DbException.getJdbcSQLException(DbException.java:622)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.message.DbException.getJdbcSQLException(DbException.java:429)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.message.DbException.get(DbException.java:194)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Database.getPageStore(Database.java:2659)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Database.open(Database.java:675)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Database.openDatabase(Database.java:307)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Database.<init>(Database.java:301)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.openSession(Engine.java:74)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.openSession(Engine.java:192)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.createSession(Engine.java:166)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.Engine.createSession(Engine.java:29)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.Driver.connect(Driver.java:69)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.ormlite.jdbc.DataSourceConnectionSource.initialize(DataSourceConnectionSource.java:104)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.ormlite.jdbc.DataSourceConnectionSource.<init>(DataSourceConnectionSource.java:71)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.BanManagerPlugin.createConnection(BanManagerPlugin.java:328)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.BanManagerPlugin.setupConnections(BanManagerPlugin.java:274)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.BanManagerPlugin.enable(BanManagerPlugin.java:168)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.bukkit.BMBukkitPlugin.onEnable(BMBukkitPlugin.java:58)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:881)
[19:21:54] [Server thread/WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:651)
[19:21:54] [Server thread/WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[19:21:54] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:748)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[19:21:54] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:21:54] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Minecraft Repository/bonkSMP/plugins/BanManager/local_bans.mv.db [1.4.200/7]
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.FileStore.open(FileStore.java:166)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.MVStore.<init>(MVStore.java:381)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
[19:21:54] [Server thread/WARN]:        ... 44 more
[19:21:54] [Server thread/WARN]: Caused by: java.nio.channels.OverlappingFileLockException
[19:21:54] [Server thread/WARN]:        at sun.nio.ch.SharedFileLockTable.checkList(Unknown Source)
[19:21:54] [Server thread/WARN]:        at sun.nio.ch.SharedFileLockTable.add(Unknown Source)
[19:21:54] [Server thread/WARN]:        at sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
[19:21:54] [Server thread/WARN]:        at java.nio.channels.FileChannel.tryLock(Unknown Source)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.h2.mvstore.FileStore.open(FileStore.java:163)
[19:21:54] [Server thread/WARN]:        ... 47 more
[19:21:54] [Server thread/INFO]: [BanManager] Disabling BanManager v7.2.2
[19:21:54] [Server thread/WARN]: java.lang.Exception: An error occurred attempting to make a database connection, please see stack trace below
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.common.BanManagerPlugin.enable(BanManagerPlugin.java:175)
[19:21:54] [Server thread/WARN]:        at me.confuser.banmanager.bukkit.BMBukkitPlugin.onEnable(BMBukkitPlugin.java:58)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[19:21:54] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:881)
[19:21:54] [Server thread/WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:651)
[19:21:54] [Server thread/WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[19:21:54] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763)
[19:21:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:748)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
[19:21:54] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[19:21:54] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:21:54] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:21:54] [Server thread/INFO]: CONSOLE: Reload complete.`

**Comment by uhBonk** [comment]
Restart fixed it, sorry for disturbing you
