### ISSUE TITLE
An error occurred at startup

### ISSUE THREAD

**Issue by misss520** [BanManagement/BanManager#972]
Below is the error log

[16:35:56 INFO]: [BanManager] Enabling BanManager v7.9.0-SNAPSHOT
[16:35:56 ERROR]: Error occurred while enabling BanManager v7.9.0-SNAPSHOT (Is it up to date?)
>java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
at me.confuser.banmanager.common.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
at me.confuser.banmanager.common.BanManagerPlugin.createConnection(BanManagerPlugin.java:292) ~[?:?]
at me.confuser.banmanager.common.BanManagerPlugin.setupConnections(BanManagerPlugin.java:282) ~[?:?]
at me.confuser.banmanager.common.BanManagerPlugin.enable(BanManagerPlugin.java:168) ~[?:?]
at me.confuser.banmanager.bukkit.BMBukkitPlugin.onEnable(BMBukkitPlugin.java:59) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]
>Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_333]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_333]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_333]
... 16 more
[16:35:57 INFO]: [BanManager] Disabling BanManager v7.9.0-SNAPSHOT

I'm sorry it's still buggy even if I use version 7.8
The core used is paper-1.8.8-445.jar
The startup environment is java8

**Comment by confuser** [comment]
Try v7.6.0 in the mean time
